pipeline: [nas, hpo, fullytrain]

nas:
    pipe_step:
        type: NasPipeStep

    search_algorithm:
        type: BackboneNas
        codec: BackboneNasCodec
        policy:
            random_ratio: 0.2
            num_mutate: 10
        range:
            max_sample: 100
            min_sample: 10
        pareto:
            object_count: 2
            max_object_ids: [0]

    search_space:
        hyperparameters:
            -   key: network.backbone.depth
                type: CATEGORY
                range: [18, 34, 50, 101]
            -   key: network.backbone.base_channel
                type: CATEGORY
                range:  [32, 48, 56, 64]
            -   key: network.backbone.doublechannel
                type: CATEGORY
                range: [3, 4]
            -   key: network.backbone.downsample
                type: CATEGORY
                range: [3, 4]
    model:
        model_desc:
            modules: ['backbone']
            backbone:
                type: ResNet

    trainer:
        type: Trainer
        with_valid: True
        epochs: 1

    dataset:
        type: Cifar10
        common:
            data_path: /cache/datasets/cifar10/

hpo:
    pipe_step:
        type: NasPipeStep

    dataset:
        ref: nas.dataset

    search_algorithm:
        type: AshaHpo
        policy:
            total_epochs: 81

    search_space:
        type: SearchSpace
        hyperparameters:
            -   key: trainer.optimizer.params.lr
                type: FLOAT_EXP
                range: [0.00001, 0.1]
            -   key: trainer.optimizer.type
                type: CATEGORY
                range: ['Adam', 'SGD']
            -   key: trainer.optimizer.params.momentum
                type: FLOAT
                range: [0.0, 0.99]
        condition:
            -   key: condition_for_sgd_momentum
                child: trainer.optimizer.params.momentum
                parent: trainer.optimizer.type
                type: EQUAL
                range: ["SGD"]

    trainer:
        type: Trainer
        epochs: 10

    model:
        models_folder: "{local_base_path}/output/nas/"

    evaluator:
        type: Evaluator
        gpu_evaluator:
            type: GpuEvaluator
            metric:
                type: accuracy

fullytrain:
    pipe_step:
        type: FullyTrainPipeStep
        models_folder: "{local_base_path}/output/nas/"

    trainer:
        type: Trainer
        epochs: 160
        optimizer:
            type: SGD
            params:
                lr: 0.1
                momentum: 0.9
                weight_decay: 0.0001
        lr_scheduler:
            type: MultiStepLR
            params:
                milestones: [60, 120]
                gamma: 0.5
        hps_folder: "{local_base_path}/output/hpo/"

    dataset:
        ref: nas.dataset
