[tool.poetry]
name = "pyicloud_z"
version = "0.9.7b2"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [
    { include = "pyicloud" },
]

[tool.poetry.dependencies]
python = "^3.6"
requests = ">=2.20.0"
keyring = ">=8.0,<=9.3.1"
"keyrings.alt" = ">=1.0,<=3.2.0"
click = ">=6.0,<=7.1.1"
six = ">=1.14.0"
tzlocal = "==2.0.0"
pytz = ">=2019.3"
certifi = ">=2019.11.28"
future = ">=0.18.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
