
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5e1063ad5ec287d5924438f916139e7333a3b75f",
 "version": "2369"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
