from wx import PyEventBinder

# Based on wxPython
# Copyright: (c) 2018 by Total Control Software
# License:   wxWindows License


def dummy_function(*args, **kwargs):
	return 0


AC_DEFAULT_STYLE = 2097152
AC_NO_AUTORESIZE = 16
class ANIDecoder: ...
ANIMATION_TYPE_ANI = 2
ANIMATION_TYPE_ANY = 3
ANIMATION_TYPE_GIF = 1
ANIMATION_TYPE_INVALID = 0
ANIM_DONOTREMOVE = 0
ANIM_TOBACKGROUND = 1
ANIM_TOPREVIOUS = 2
ANIM_UNSPECIFIED = -1
AboutBox = dummy_function
class AboutDialogInfo: ...
class Animation: ...
class AnimationCtrl: ...
AnimationCtrlNameStr = b'animationctrl'
class AnimationDecoder: ...
class AnimationDecoderList: ...
class AnimationDecoderList_iterator: ...
class AnimationDisposal: ...
class AnimationType: ...
class BannerWindow: ...
BannerWindowNameStr = b'bannerwindow'
class BitmapComboBox: ...
BitmapComboBoxNameStr = b'bitmapComboBox'
CAL_BORDER_NONE = 0
CAL_BORDER_ROUND = 2
CAL_BORDER_SQUARE = 1
CAL_HITTEST_DAY = 2
CAL_HITTEST_DECMONTH = 4
CAL_HITTEST_HEADER = 1
CAL_HITTEST_INCMONTH = 3
CAL_HITTEST_NOWHERE = 0
CAL_HITTEST_SURROUNDING_WEEK = 5
CAL_HITTEST_WEEK = 6
CAL_MONDAY_FIRST = 1
CAL_NO_MONTH_CHANGE = 12
CAL_NO_YEAR_CHANGE = 4
CAL_SEQUENTIAL_MONTH_SELECTION = 16
CAL_SHOW_HOLIDAYS = 2
CAL_SHOW_SURROUNDING_WEEKS = 32
CAL_SHOW_WEEK_NUMBERS = 64
CAL_SUNDAY_FIRST = 128
class CalculateLayoutEvent: ...
class CalendarCtrl: ...
class CalendarDateAttr: ...
class CalendarDateBorder: ...
class CalendarEvent: ...
class CalendarHitTestResult: ...
CalendarNameStr = b'CalendarCtrl'
class CommandLinkButton: ...
CreateFileTipProvider = dummy_function
DP_ALLOWNONE = 8
DP_DEFAULT = 0
DP_DROPDOWN = 2
DP_SHOWCENTURY = 4
DP_SPIN = 1
class DateEvent: ...
class DatePickerCtrl: ...
EL_ALLOW_DELETE = 1024
EL_ALLOW_EDIT = 512
EL_ALLOW_NEW = 256
EL_DEFAULT_STYLE = 1792
EL_NO_REORDER = 2048
class EditableListBox: ...
EditableListBoxNameStr = b'editableListBox'
class ExtHelpController: ...
class GIFDecoder: ...
GenericAboutBox = dummy_function
class GenericAnimationCtrl: ...
class GenericCalendarCtrl: ...
class GenericDatePickerCtrl: ...
HL_ALIGN_CENTRE = 8
HL_ALIGN_LEFT = 2
HL_ALIGN_RIGHT = 4
HL_CONTEXTMENU = 1
HL_DEFAULT_STYLE = 2097161
class HyperlinkCtrl: ...
HyperlinkCtrlNameStr = b'hyperlink'
class HyperlinkEvent: ...
class Joystick: ...
LAYOUT_BOTTOM = 4
LAYOUT_HORIZONTAL = 0
LAYOUT_LEFT = 2
LAYOUT_NONE = 0
LAYOUT_RIGHT = 3
LAYOUT_TOP = 1
LAYOUT_VERTICAL = 1
class LayoutAlgorithm: ...
class LayoutAlignment: ...
class LayoutOrientation: ...
class NotificationMessage: ...
ODCB_DCLICK_CYCLES = 256
ODCB_PAINTING_CONTROL = 1
ODCB_PAINTING_SELECTED = 2
ODCB_STD_CONTROL_PAINT = 4096
class OwnerDrawnComboBox: ...
class OwnerDrawnComboBoxPaintingFlags: ...
PROPSHEET_BUTTONTOOLBOOK = 32
PROPSHEET_CHOICEBOOK = 8
PROPSHEET_DEFAULT = 1
PROPSHEET_LISTBOOK = 16
PROPSHEET_NOTEBOOK = 2
PROPSHEET_SHRINKTOFIT = 256
PROPSHEET_TOOLBOOK = 4
PROPSHEET_TREEBOOK = 64
class PropertySheetDialog: ...
class PropertySheetDialogFlags: ...
class PseudoDC: ...
class PyWizardPage: ...
class QueryLayoutInfoEvent: ...
class RichToolTip: ...
SASH_BOTTOM = 2
SASH_LEFT = 3
SASH_NONE = 100
SASH_RIGHT = 1
SASH_STATUS_OK = 0
SASH_STATUS_OUT_OF_RANGE = 1
SASH_TOP = 0
SOUND_ASYNC = 1
SOUND_LOOP = 2
SOUND_SYNC = 0
SPLASH_CENTER_ON_PARENT = 1
SPLASH_CENTER_ON_SCREEN = 2
SPLASH_CENTRE_ON_PARENT = 1
SPLASH_CENTRE_ON_SCREEN = 2
SPLASH_NO_CENTER = 0
SPLASH_NO_CENTRE = 0
SPLASH_NO_TIMEOUT = 0
SPLASH_TIMEOUT = 4
SW_3D = 192
SW_3DBORDER = 128
SW_3DSASH = 64
SW_BORDER = 32
SW_NOBORDER = 0
class SashDragStatus: ...
class SashEdgePosition: ...
class SashEvent: ...
class SashLayoutWindow: ...
class SashWindow: ...
ShowTip = dummy_function
class Sound: ...
class SplashScreen: ...
TBI_CUSTOM_STATUSITEM = 1
TBI_DEFAULT_TYPE = 0
TBI_DOCK = 0
TP_DEFAULT = 0
class TaskBarIcon: ...
class TaskBarIconEvent: ...
class TaskBarIconType: ...
class TimePickerCtrl: ...
TimePickerCtrlNameStr = 'timectrl'
class TipKind: ...
TipKind_Auto = 7
TipKind_Bottom = 5
TipKind_BottomLeft = 4
TipKind_BottomRight = 6
TipKind_None = 0
TipKind_Top = 2
TipKind_TopLeft = 1
TipKind_TopRight = 3
class TipProvider: ...
USE_JOYSTICK = 1
WIZARD_EX_HELPBUTTON = 16
WIZARD_HALIGN_CENTRE = 16
WIZARD_HALIGN_LEFT = 8
WIZARD_HALIGN_RIGHT = 32
WIZARD_TILE = 64
WIZARD_VALIGN_BOTTOM = 4
WIZARD_VALIGN_CENTRE = 2
WIZARD_VALIGN_TOP = 1
class Wizard: ...
class WizardEvent: ...
class WizardPage: ...
class WizardPageSimple: ...
wxEVT_CALCULATE_LAYOUT = 10315
wxEVT_CALENDAR_DAY_CHANGED = 10250
wxEVT_CALENDAR_DOUBLECLICKED = 10247
wxEVT_CALENDAR_MONTH_CHANGED = 10251
wxEVT_CALENDAR_PAGE_CHANGED = 10246
wxEVT_CALENDAR_SEL_CHANGED = 10245
wxEVT_CALENDAR_WEEKDAY_CLICKED = 10248
wxEVT_CALENDAR_WEEK_CLICKED = 10249
wxEVT_CALENDAR_YEAR_CHANGED = 10252
wxEVT_COMMAND_HYPERLINK = 10303
wxEVT_DATE_CHANGED = 10243
wxEVT_HYPERLINK = 10303
wxEVT_QUERY_LAYOUT_INFO = 10314
wxEVT_SASH_DRAGGED = 10276
wxEVT_TASKBAR_BALLOON_CLICK = 10139
wxEVT_TASKBAR_BALLOON_TIMEOUT = 10138
wxEVT_TASKBAR_CLICK = 10134
wxEVT_TASKBAR_LEFT_DCLICK = 10136
wxEVT_TASKBAR_LEFT_DOWN = 10132
wxEVT_TASKBAR_LEFT_UP = 10133
wxEVT_TASKBAR_MOVE = 10131
wxEVT_TASKBAR_RIGHT_DCLICK = 10137
wxEVT_TASKBAR_RIGHT_DOWN = 10134
wxEVT_TASKBAR_RIGHT_UP = 10135
wxEVT_TIME_CHANGED = 10244
wxEVT_WIZARD_BEFORE_PAGE_CHANGED = 10309
wxEVT_WIZARD_CANCEL = 10310
wxEVT_WIZARD_FINISHED = 10311
wxEVT_WIZARD_HELP = 10312
wxEVT_WIZARD_PAGE_CHANGED = 10307
wxEVT_WIZARD_PAGE_CHANGING = 10308
wxEVT_WIZARD_PAGE_SHOWN = 10313
EVT_CALCULATE_LAYOUT = PyEventBinder()
EVT_CALENDAR = PyEventBinder()
EVT_CALENDAR_DAY = PyEventBinder()
EVT_CALENDAR_MONTH = PyEventBinder()
EVT_CALENDAR_PAGE_CHANGED = PyEventBinder()
EVT_CALENDAR_SEL_CHANGED = PyEventBinder()
EVT_CALENDAR_WEEKDAY_CLICKED = PyEventBinder()
EVT_CALENDAR_WEEK_CLICKED = PyEventBinder()
EVT_CALENDAR_YEAR = PyEventBinder()
EVT_DATE_CHANGED = PyEventBinder()
EVT_HYPERLINK = PyEventBinder()
EVT_QUERY_LAYOUT_INFO = PyEventBinder()
EVT_SASH_DRAGGED = PyEventBinder()
EVT_SASH_DRAGGED_RANGE = PyEventBinder()
EVT_TASKBAR_BALLOON_CLICK = PyEventBinder()
EVT_TASKBAR_BALLOON_TIMEOUT = PyEventBinder()
EVT_TASKBAR_CLICK = PyEventBinder()
EVT_TASKBAR_LEFT_DCLICK = PyEventBinder()
EVT_TASKBAR_LEFT_DOWN = PyEventBinder()
EVT_TASKBAR_LEFT_UP = PyEventBinder()
EVT_TASKBAR_MOVE = PyEventBinder()
EVT_TASKBAR_RIGHT_DCLICK = PyEventBinder()
EVT_TASKBAR_RIGHT_DOWN = PyEventBinder()
EVT_TASKBAR_RIGHT_UP = PyEventBinder()
EVT_TIME_CHANGED = PyEventBinder()
EVT_WIZARD_BEFORE_PAGE_CHANGED = PyEventBinder()
EVT_WIZARD_CANCEL = PyEventBinder()
EVT_WIZARD_FINISHED = PyEventBinder()
EVT_WIZARD_HELP = PyEventBinder()
EVT_WIZARD_PAGE_CHANGED = PyEventBinder()
EVT_WIZARD_PAGE_CHANGING = PyEventBinder()
EVT_WIZARD_PAGE_SHOWN = PyEventBinder()
NullAnimation = Animation()
