from wx import PyEventBinder

# Based on wxPython
# Copyright: (c) 2018 by Total Control Software
# License:   wxWindows License


def dummy_function(*args, **kwargs):
	return 0


USE_WEBVIEW = 1
WEBVIEWIE_EMU_DEFAULT = 0
WEBVIEWIE_EMU_IE10 = 10000
WEBVIEWIE_EMU_IE10_FORCE = 10001
WEBVIEWIE_EMU_IE11 = 11000
WEBVIEWIE_EMU_IE11_FORCE = 11001
WEBVIEWIE_EMU_IE7 = 7000
WEBVIEWIE_EMU_IE8 = 8000
WEBVIEWIE_EMU_IE8_FORCE = 8888
WEBVIEWIE_EMU_IE9 = 9000
WEBVIEWIE_EMU_IE9_FORCE = 9999
WEBVIEW_FIND_BACKWARDS = 16
WEBVIEW_FIND_DEFAULT = 0
WEBVIEW_FIND_ENTIRE_WORD = 2
WEBVIEW_FIND_HIGHLIGHT_RESULT = 8
WEBVIEW_FIND_MATCH_CASE = 4
WEBVIEW_FIND_WRAP = 1
WEBVIEW_NAV_ACTION_NONE = 0
WEBVIEW_NAV_ACTION_OTHER = 2
WEBVIEW_NAV_ACTION_USER = 1
WEBVIEW_NAV_ERR_AUTH = 2
WEBVIEW_NAV_ERR_CERTIFICATE = 1
WEBVIEW_NAV_ERR_CONNECTION = 0
WEBVIEW_NAV_ERR_NOT_FOUND = 4
WEBVIEW_NAV_ERR_OTHER = 7
WEBVIEW_NAV_ERR_REQUEST = 5
WEBVIEW_NAV_ERR_SECURITY = 3
WEBVIEW_NAV_ERR_USER_CANCELLED = 6
WEBVIEW_RELOAD_DEFAULT = 0
WEBVIEW_RELOAD_NO_CACHE = 1
WEBVIEW_ZOOM_LARGE = 3
WEBVIEW_ZOOM_LARGEST = 4
WEBVIEW_ZOOM_MEDIUM = 2
WEBVIEW_ZOOM_SMALL = 1
WEBVIEW_ZOOM_TINY = 0
WEBVIEW_ZOOM_TYPE_LAYOUT = 0
WEBVIEW_ZOOM_TYPE_TEXT = 1
class WebView: ...
class WebViewArchiveHandler: ...
WebViewBackendDefault = b'wxWebViewWebKit'
WebViewBackendIE = b'wxWebViewIE'
WebViewBackendWebKit = b'wxWebViewWebKit'
WebViewDefaultURLStr = b'about:blank'
class WebViewEvent: ...
class WebViewFSHandler: ...
class WebViewFactory: ...
class WebViewFindFlags: ...
class WebViewHandler: ...
class WebViewHistoryItem: ...
class WebViewIE_EmulationLevel: ...
WebViewNameStr = b'wxWebView'
class WebViewNavigationActionFlags: ...
class WebViewNavigationError: ...
class WebViewReloadFlags: ...
class WebViewZoom: ...
class WebViewZoomType: ...
wxEVT_COMMAND_WEBVIEW_ERROR = 10351
wxEVT_COMMAND_WEBVIEW_LOADED = 10350
wxEVT_COMMAND_WEBVIEW_NAVIGATED = 10349
wxEVT_COMMAND_WEBVIEW_NAVIGATING = 10348
wxEVT_COMMAND_WEBVIEW_NEWWINDOW = 10352
wxEVT_COMMAND_WEBVIEW_TITLE_CHANGED = 10353
wxEVT_WEBVIEW_ERROR = 10351
wxEVT_WEBVIEW_LOADED = 10350
wxEVT_WEBVIEW_NAVIGATED = 10349
wxEVT_WEBVIEW_NAVIGATING = 10348
wxEVT_WEBVIEW_NEWWINDOW = 10352
wxEVT_WEBVIEW_TITLE_CHANGED = 10353
EVT_WEBVIEW_ERROR = PyEventBinder()
EVT_WEBVIEW_LOADED = PyEventBinder()
EVT_WEBVIEW_NAVIGATED = PyEventBinder()
EVT_WEBVIEW_NAVIGATING = PyEventBinder()
EVT_WEBVIEW_NEWWINDOW = PyEventBinder()
EVT_WEBVIEW_TITLE_CHANGED = PyEventBinder()
