from wx import PyEventBinder

# Based on wxPython
# Copyright: (c) 2018 by Total Control Software
# License:   wxWindows License


def dummy_function(*args, **kwargs):
	return 0


HF_BOOKMARKS = 16
HF_CONTENTS = 2
HF_DEFAULT_STYLE = 95
HF_DIALOG = 65536
HF_EMBEDDED = 32768
HF_FLAT_TOOLBAR = 128
HF_FRAME = 131072
HF_ICONS_BOOK = 512
HF_ICONS_BOOK_CHAPTER = 1024
HF_ICONS_FOLDER = 0
HF_INDEX = 4
HF_MERGE_BOOKS = 256
HF_MODAL = 262144
HF_OPEN_FILES = 32
HF_PRINT = 64
HF_SEARCH = 8
HF_TOOLBAR = 1
HLB_DEFAULT_STYLE = 134217728
HLB_MULTIPLE = 64
HTML_ALIGN_BOTTOM = 8
HTML_ALIGN_CENTER = 1
HTML_ALIGN_JUSTIFY = 16
HTML_ALIGN_LEFT = 0
HTML_ALIGN_RIGHT = 2
HTML_ALIGN_TOP = 4
HTML_BLOCK = 1
HTML_CLR_BACKGROUND = 2
HTML_CLR_FOREGROUND = 1
HTML_CLR_TRANSPARENT_BACKGROUND = 4
HTML_COND_ISANCHOR = 1
HTML_COND_ISIMAGEMAP = 2
HTML_COND_USER = 10000
HTML_FIND_EXACT = 1
HTML_FIND_NEAREST_AFTER = 4
HTML_FIND_NEAREST_BEFORE = 2
HTML_INDENT_ALL = 240
HTML_INDENT_BOTTOM = 128
HTML_INDENT_HORIZONTAL = 48
HTML_INDENT_LEFT = 16
HTML_INDENT_RIGHT = 32
HTML_INDENT_TOP = 64
HTML_INDENT_VERTICAL = 192
HTML_OPEN = 0
HTML_REDIRECT = 2
HTML_SCRIPT_NORMAL = 0
HTML_SCRIPT_SUB = 1
HTML_SCRIPT_SUP = 2
HTML_SEL_CHANGING = 2
HTML_SEL_IN = 1
HTML_SEL_OUT = 0
HTML_UNITS_PERCENT = 2
HTML_UNITS_PIXELS = 1
HTML_URL_IMAGE = 1
HTML_URL_OTHER = 2
HTML_URL_PAGE = 0
HW_DEFAULT_STYLE = 4
HW_NO_SELECTION = 8
HW_SCROLLBAR_AUTO = 4
HW_SCROLLBAR_NEVER = 2
class HtmlBookRecArray: ...
class HtmlBookRecord: ...
class HtmlCell: ...
class HtmlCellEvent: ...
class HtmlColourCell: ...
class HtmlContainerCell: ...
class HtmlDCRenderer: ...
class HtmlEasyPrinting: ...
class HtmlFilter: ...
class HtmlFontCell: ...
class HtmlHelpController: ...
class HtmlHelpData: ...
class HtmlHelpDataItem: ...
class HtmlHelpDataItems: ...
class HtmlHelpDialog: ...
class HtmlHelpFrame: ...
class HtmlHelpWindow: ...
class HtmlLinkEvent: ...
class HtmlLinkInfo: ...
class HtmlListBox: ...
HtmlListBoxNameStr = b'htmlListBox'
class HtmlModalHelp: ...
class HtmlOpeningStatus: ...
class HtmlParser: ...
class HtmlPrintout: ...
class HtmlRenderingInfo: ...
class HtmlRenderingState: ...
class HtmlRenderingStyle: ...
class HtmlScriptMode: ...
class HtmlSelection: ...
class HtmlSelectionState: ...
class HtmlTag: ...
class HtmlTagHandler: ...
class HtmlURLType: ...
class HtmlWidgetCell: ...
class HtmlWinParser: ...
HtmlWinParser_AddTagHandler = dummy_function
class HtmlWinTagHandler: ...
class HtmlWindow: ...
class HtmlWindowInterface: ...
class HtmlWordCell: ...
class HtmlWordWithTabsCell: ...
ID_HTML_BACK = 6010
ID_HTML_BOOKMARKSADD = 6019
ID_HTML_BOOKMARKSLIST = 6018
ID_HTML_BOOKMARKSREMOVE = 6020
ID_HTML_COUNTINFO = 6033
ID_HTML_DOWN = 6014
ID_HTML_FORWARD = 6011
ID_HTML_HELPFRAME = 6000
ID_HTML_INDEXBUTTON = 6025
ID_HTML_INDEXBUTTONALL = 6026
ID_HTML_INDEXLIST = 6023
ID_HTML_INDEXPAGE = 6022
ID_HTML_INDEXTEXT = 6024
ID_HTML_NOTEBOOK = 6027
ID_HTML_OPENFILE = 6016
ID_HTML_OPTIONS = 6017
ID_HTML_PANEL = 6009
ID_HTML_PRINT = 6015
ID_HTML_SEARCHBUTTON = 6031
ID_HTML_SEARCHCHOICE = 6032
ID_HTML_SEARCHLIST = 6030
ID_HTML_SEARCHPAGE = 6028
ID_HTML_SEARCHTEXT = 6029
ID_HTML_TREECTRL = 6021
ID_HTML_UP = 6013
ID_HTML_UPNODE = 6012
INT_MAX = 2147483647
PAGE_ALL = 2
PAGE_EVEN = 1
PAGE_ODD = 0
class SimpleHtmlListBox: ...
SimpleHtmlListBoxNameStr = b'simpleHtmlListBox'
wxEVT_COMMAND_HTML_CELL_CLICKED = 10345
wxEVT_COMMAND_HTML_CELL_HOVER = 10346
wxEVT_COMMAND_HTML_LINK_CLICKED = 10347
wxEVT_HTML_CELL_CLICKED = 10345
wxEVT_HTML_CELL_HOVER = 10346
wxEVT_HTML_LINK_CLICKED = 10347
EVT_HTML_CELL_CLICKED = PyEventBinder()
EVT_HTML_CELL_HOVER = PyEventBinder()
EVT_HTML_LINK_CLICKED = PyEventBinder()
