
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-11T15:56:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f3e0654c79bbe414b65bf52978c88f3ba37f1b93",
 "version": "v0.0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
