[tool.poetry]
name = "AlekSIS-App-CSVImport"
version = "2.0a1"
packages = [
    { include = "aleksis" }
]
readme = "README.rst"
include = ["CHANGELOG.rst", "LICENCE.rst", "aleksis/**/locale/*.mo"]

description = "AlekSIS (School Information System) — App for SchILD-NRW interaction"
authors = ["Dominik George <dominik.george@teckids.org>", "Jonathan Weth <dev@jonathanweth.de>"]
license = "EUPL-1.2"
homepage = "https://aleksis.org/"
repository = "https://edugit.org/AlekSIS/Onboarding/AlekSIS-App-CSVImport"
documentation = "https://aleksis.edugit.io/AlekSIS/docs/html/"
classifiers = [
    "Environment :: Web Environment",
    "Intended Audience :: Education",
    "Topic :: Education"
]

[[tool.poetry.source]]
name = "gitlab"
url = "https://edugit.org/api/v4/projects/461/packages/pypi/simple"
secondary = true

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.0"
phonenumbers = "^8.10"
dateparser = "^0.7.6"
pycountry = "^20.7.3"
aleksis-core = "^2.0a3.dev0"
aleksis-app-chronos = "^2.0a3.dev0"

[tool.poetry.dev-dependencies]
aleksis-builddeps = "*"

[tool.poetry.plugins."aleksis.app"]
csv_import = "aleksis.apps.csv_import.apps:CSVImportConfig"

[tool.black]
line-length = 100
exclude = "/migrations/"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
