name: QC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    continue-on-error: true
    name: black, flake8, twine
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v2

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ubuntu-latest

    - name: Upgrade pip, wheel
      run: python -m pip install --upgrade pip wheel

    - name: Check "black" code style
      run: |
        pip install black
        black --check .

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --count --max-complexity=15 --show-source --statistics

    - name: Build package
      run: |
        pip install twine wheel
        python3 setup.py bdist_wheel sdist
        twine check dist/*

  mypy-sphinx:
    continue-on-error: true
    name: mypy, sphinx docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v2

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ubuntu-latest

    - name: Upgrade pip, wheel
      run: python -m pip install --upgrade pip wheel

    - name: Install the Python package and dependencies
      run: pip install .[doc,hist,tests]

    - name: Check typing with mypy
      run: |
        pip install mypy
        mypy .

    - name: Build documentation using Sphinx
      run: make --directory=doc html
