# Generated by Django 3.1.3 on 2020-11-09 20:30

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kapnoc_tests2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmarkdownpage',
            name='body',
            field=martor.models.MartorField(),
        ),
    ]
