[tool.poetry]
name = "hycli"
version = "0.3.27"
description = "Interface package to convert invoice to xml by requesting different Hypatos services."
authors = ["Dylan Bartels <dylan.bartels@hypatos.ai>"]

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.poetry.dependencies]
python = "^3.6.12"
requests = "^2.22.0"
xmltodict = "^0.12.0"
click = "^7.0"
filetype = "^1.0.5"
click-log = "^0.3.2"
XlsxWriter = "^1.2.7"
toml = "^0.10.0"
halo = "^0.0.29"
pandas = "^1.0.5"

[tool.poetry.dev-dependencies]
rope = "^0.16.0"
flake8 = "^3.8.4"
pytest = "^5.3.5"
black = "^19.10b0"
bump2version = "^1.0.0"

[tool.poetry.scripts]
hycli = "hycli.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
