
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-18T11:21:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb50eda62cadb71622a7c31c9884ff4bfd173ccf",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
