general:
    parallel_search: True
    backend: pytorch
    quota:
        restrict:
            flops: 2.5

pipeline: [random, mutate]
#pipeline: [random, mutate, fully_train]

random:
    pipe_step:
        type: NasPipeStep

    dataset:
        type: Cityscapes
        common:
            root_dir: /cache/datasets/VOC2012
        train:
            list_file: train.txt
            batch_size: 16
            shuffle: true
            Rescale:
                size: 512
            RandomMirror: true
            RandomColor:
                color_factor: [0.95, 1.05]
                contrast_factor: [0.95, 1.05]
                brightness_factor: [0.95, 1.05]
            RandomGaussianBlur:
                kernel_size: 3
            RandomRotation:
                rotation_factor: [-10, 10]
                border_value: [0.485, 0.456, 0.406]
                fill_label: 255
            Normalization:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
        val:
            list_file: val.txt
            Rescale:
                size: 512
            Normalization:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]

    search_space:
        type: SearchSpace
        modules: ['custom']
        custom:
            type: AdelaideFastNAS
            backbone_load_path: ~
            backbone_out_sizes: [24, 32, 96, 320]
            op_names: [conv1x1, conv3x3, sep_conv_3x3, sep_conv_5x5, conv3x3_dil3, sep_conv_3x3_dil3, sep_conv_5x5_dil6]
            agg_size: 64
            aux_cell: false
            sep_repeats: 1
            agg_concat: true
            num_classes: 21

    search_algorithm:
        type: AdelaideRandom
        codec: AdelaideCodec
        max_sample: 5 #10

    trainer:
        type: Trainer
        callbacks: AdelaideEATrainerCallback
        cuda: true
        distributed: False
        seed: 0
        epochs: 1 #5
        optimizer:
            type: Adam
            params:
                lr: !!float 5e-5
        lr_scheduler:
            type: StepLR
            params:
                step_size: 5
                gamma: 0.5
        loss:
            type: CrossEntropyLoss
            params:
                ignore_index: 255
                is_grad: False
                sparse: True
        metric:
            type: IoUMetric
            params:
                num_class: 21

mutate:
    pipe_step:
        type: NasPipeStep

    dataset:
        ref: random.dataset

    search_space:
           ref: random.search_space

    search_algorithm:
        type: AdelaideMutate
        codec: AdelaideCodec
        max_sample: 5 #10

    trainer:
        ref: random.trainer
        callbacks: AdelaideEATrainerCallback
        save_model_desc: True

fully_train:
    pipe_step:
        type: FullyTrainPipeStep
        models_folder: "{local_base_path}/output/mutate/"

    dataset:
        ref: random.dataset

    search_space:
        ref: random.search_space
        custom:
            sep_repeats: 2

    trainer:
        ref: random.trainer
        callbacks: AdelaideEATrainerCallback
        model_statistics: True
        epochs: 10

benchmark:
    pipeline: [random, mutate, fully_train, benchmark_VOC2012]
    random:
        search_space:
            custom:
                backbone_load_path: /cache/models/mobilenet_v2-b0353104.pth
        search_algorithm:
            max_sample: 100
        trainer:
            epochs: 6
    mutate:
        search_algorithm:
            max_sample: 100
    fully_train:
        dataset:
            train:
                batch_size: 24
        trainer:
            epochs: 100
    benchmark_VOC2012:
        pipe_step:
            type: BenchmarkPipeStep
            models_folder: "{local_base_path}/output/fully_train/"
        dataset:
            ref: random.dataset
        evaluator:
            type: Evaluator
            gpu_evaluator:
                type: GpuEvaluator
                metric:
                    type: IoUMetric
                    num_class: 21
