# Generated by Django 3.1.3 on 2020-11-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ievv_logging', '0004_auto_20191124_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ievvloggingeventitem',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
