[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "gitprovenance"
author = "Pauli Virtanen"
author-email = "pav@iki.fi"
home-page = "https://github.com/pv/gitprovenance/"
requires = []
description-file = "README.rst"
classifiers=[
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.5"
