home:
  name: ""
  applications:
    - class: conky
misc: "•"
desktops:
  - name: ""
    extra_name: ''
    order: 220
    applications:
      - class: Chromium
  - name: ﭮ
    extra_name: discord
    order: 210
    applications:
      - class: discord
  - name: ""
    extra_name: pycharm
    order: 320
    applications:
      - class: jetbrains-pycharm
  - name: ""
    extra_name: phpstorm
    order: 315
    applications:
      - class: jetbrains-phpstorm
  - name: ""
    extra_name: webstorm
    order: 310
    applications:
      - class: jetbrains-webstorm
  - name: ""
    extra_name: idea
    order: 330
    applications:
      - class: jetbrains-idea
  - name: ""
    extra_name: VS Code
    order: 340
    applications:
      - class: code-oss
  - name: MMC
    extra_name: ''
    order: 410
    applications:
      - class: MultiMC5
  - name: MC
    extra_name: "%instance"
    order: 420
    applications:
      - class: Minecraft .*
  - name: TEST
    extra_name: EXTRA
    order: 6
    applications:
      - class: Gnome-calculator
  - name: TEST
    extra_name: EXTRATWO
    order: 6
    applications:
      - class: Qalculate-gtk
