general:
    parallel_search: False
    parallel_fully_train: False
    backend: pytorch

# pipeline: [nas]
pipeline: [nas ,fully_train]

nas:
    pipe_step:
        type: NasPipeStep

    dataset:
        type: Cifar10
        common:
            data_path: /cache/datasets/cifar10/
            train_portion: 0.9  
        train:
            batch_size: 128
        test:
            batch_size: 256

    search_algorithm:
        type: QuantEA
        codec: QuantCodec
        policy:
            length: 66
            num_generation: 50
            num_individual: 16
            random_models: 32

    search_space:
        type: SearchSpace
        modules: ['backbone']
        bit_candidates: [4, 8]
        backbone:
            type: MobileNetV3Small

    trainer:
        type: Trainer
        callbacks: QuantTrainerCallback
        epochs: 1
        optimizer:
            type: SGD
            params:
                lr: 0.1
                momentum: 0.9
                weight_decay: !!float 1e-4
        lr_scheduler:
            type: MultiStepLR
            params:
                milestones: [5, 10, 15]
                gamma: 0.1
        seed: 10
        save_weight: False
        limits:
            flop_range: [!!float 0, !!float 1e10]

fully_train:
    pipe_step:
        type: FullyTrainPipeStep
        models_folder: "{local_base_path}/output/nas/"
    dataset:
        ref: nas.dataset
        common:
            train_portion: 1.0
        train: 
            shuffle: True
    trainer:
        ref: nas.trainer
        callbacks: QuantTrainerCallback
        epochs: 300
        lr_scheduler:
            type: MultiStepLR
            params:
                milestones: [200, 300, 375]
                gamma: 0.1

benchmark:
    pipeline: [nas, fully_train, benchmark_cifar10]
    fully_train:
        trainer:
            epochs: 400
    benchmark_cifar10:
        pipe_step:
            type: BenchmarkPipeStep
            models_folder: "{local_base_path}/output/fully_train/"
        dataset:
            ref: nas.dataset
            common:
                train_portion: 1.0
        evaluator:
            type: Evaluator
            gpu_evaluator:
                type: GpuEvaluator
                metric:
                    type: accuracy
