
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-16T10:47:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b085cc228ab88bb26d34b82d2b89e098591ab64",
 "version": "0.0.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
