
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-10T15:42:17+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "72d2586ac67f75008039b620762e5cec7de78c89",
 "version": "v1.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
