name: Test (Windows)

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pip install hypothesis
          pytest tests\test_cli.py --run-slow
