[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "lagom"
author = "meadsteve"
author-email = "meadsteve@gmail.com"
home-page = "https://lagom-di.readthedocs.io/en/stable/"
requires-python="~=3.6"
description-file="README.md"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
]

[tool.flit.sdist]
include = ["lagom/githash.txt"]
exclude = ["tests/", "scripts/"]

[tool.flit.metadata.requires-extra]
env = ["pydantic >=1.0.0,<2.0.0"]
