---
#
#############################################
#
# Key of the 'clouds' variable containing the credentials
# where OpenStack resources are provisionned. The 'clouds'
# variable is defined in the clouds.yml file.
#
openstack_cloud: production
