# Analysis Ready Data (ARD)
ARD_BASE_URL: http://lcmap.cr.usgs.gov
ARD_CU: ARD_CU_C01_V01

# CCDC - Object storage configuration
S3_URL: http://lsdslb.cr.usgs.gov:7484
S3_BUCKET: ard-cu-c01-v01-aux-cu-v01-ccdc-1-0
S3_GET_TIMEOUT: 9
