[tool.poetry]
name = "nkit"
version = "0.1.2"
description = ""
authors = ["Ankit <ankitsaini100205@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.scripts]
nkit = "nkit.main:app"

[tool.poetry.dependencies]
python = "^3.6"
typer = {extras = ["all"], version = "^0.3.2"}
httpx = "^0.16.1"
dataset = "^1.3.2"
arrow = "^0.17.0"
pydantic = "^1.7.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-env = "^0.6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
