version: '3.6'
services:

  app:
    image: elixircloud/foca-petstore:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - mongodb
      - rabbitmq
    command: bash -c "python app.py"
    ports:
      - "80:8080"

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    links:
      - mongodb
    ports:
      - "5672:5672"

  mongodb:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/petstore/db:/data/db
    ports:
      - "27017:27017"
