resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: astrofrog
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'

jobs:

- template: run-tox-env.yml@OpenAstronomy
  parameters:

    envs:

    - linux: codestyle
      name: codestyle

    - windows: py36-test-cli
      name: windows_py36_test_cli

    - macos: py37-test-cli
      name: macos_py37_test_cli

    - linux: py38-test-cli
      name: linux_py38_test_cli

    - windows: py36-test-config
      name: windows_py36_test_config

    - macos: py37-test-config
      name: macos_py37_test_config

    - linux: py38-test-config
      name: linux_py38_test_config


- template: publish.yml@OpenAstronomy
  parameters:
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
      pypi_connection_name : 'pypi_endpoint'
    targets:
    - sdist
    - wheels_universal
    dependsOn:
    - codestyle
    - windows_py36_test_cli
    - macos_py37_test_cli
    - linux_py38_test_cli
    - windows_py36_test_config
    - macos_py37_test_config
    - linux_py38_test_config
