[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "flama"
version = "0.16.0"
description = "Fire up your API"
authors = ["José Antonio Perdiguero López <perdy@perdy.io>"]
license = "GPL-3.0+"
readme = "README.md"
repository = "https://github.com/perdy/flama"
keywords = ["starlette", "api", "components", "schema", "openapi", "async"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Application Frameworks"
]
include = []
exclude = []

[tool.poetry.dependencies]
python = "^3.6"
starlette = ">=0.14.0,<1.0.0"
marshmallow = "^3.0"
python-forge = {version = "^18.6",optional = true}
apispec = {version = "^4.0",optional = true}
pyyaml = {version = "^5.0",optional = true}
databases = {version = "^0.4.0",optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-xdist = "^1.22"
pytest-cov = "^2.0"
clinner = "^1.12"
ipython = "^7.0"
ipdb = "^0.11"
isort = "^4.3"
python-multipart = "^0.0.5"
pyyaml = "^5.0"
apispec = "^4.0"
flake8 = "^3.7"
pytest-asyncio = "^0.10"
sqlalchemy-utils = "^0.33"
python-forge = "^18.6"
mkdocs = "^1.0"
mkdocs-material = "^4.0"
black = {version = "^19.3b0",allow-prereleases = true}
uvicorn = ">=0.10.0,<1.0.0"
aiosqlite = ">=0.11.0,<1.0.0"
requests = "^2.22.0"
databases = ">=0.4.0,<1.0.0"

[tool.poetry.extras]
full = ["apispec","pyyaml","python-forge","sqlalchemy","databases"]
pagination = ["python-forge"]
schema = ["apispec","pyyaml"]
resources = ["databases"]

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | build
  | dist
)/
'''
