
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-14T12:11:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "526c946d5f5178a29a48aa1fc5643d6cac9d8ebb",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
