[tool.poetry]
name = "capablerobot_usbregister"
version = "1.3.1.2"
description = "Windows command line tool to assist in registering USB drivers"
authors = ["Chris Osterwood <osterwood@capablerobot.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/CapableRobot/CapableRobot_USBRegister"
keywords = ["usb", "hardware"]
include = ["LICENSE", "requirements.txt"]

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
usbregister = "capablerobot_usbregister.main:console"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
