[tool.poetry]
name = "tgtypes"
version = "0.1.1"
packages = [
    { include = "tgtypes" }
]
description = "Unified Python models for Telegram Messenger."
authors = ["JosXa <joscha.goetzer@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/JosXa/tgintegration"
keywords = ["telegram", "python3", "models", "abstractions"]
classifiers = [
    "Typing :: Typed",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: Implementation :: CPython"
]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = { version = "^1.6.1" }
#"ruamel.yaml" = "^0.16.12"

[tool.poetry.dev-dependencies]
black = { version = ">=20.8b1", python = "^3.8", markers = "platform_python_implementation == 'CPython'" }
mypy = ">0.770"
birdseye = "^0.8.3"
mkinit = "^0.2.0"
typer = "^0.3.1"
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "^2.10.1"
pre-commit = "^2.7.1"
devtools = { extras = ["pygments"], version = "^0.6" }
pytest-mock = "^3.3.1"
asynctest = "^0.13.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
