[tool.poetry]
name = "gera2ld.aioproxy"
version = "0.3.4"
description = ""
authors = ["Gerald <gera2ld@163.com>"]
license = "MIT"
repository = "https://github.com/gera2ld/aioproxy"
readme = 'README.md'
packages = [
  { include = 'gera2ld' },
]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0"
"gera2ld.socks" = "^0.4.3"
importlib_metadata = "^1.7.0"

[tool.poetry.dev-dependencies]
jedi = "^0.17.2"
pylint = "^2.6.0"
rope = "^0.18.0"
yapf = "^0.30.0"

[tool.poetry.scripts]
aioproxy = "gera2ld.aioproxy.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

