[tool.poetry]
name = "termynal"
version = "0.2.0"
description = ""
authors = ["Danil Akhtarov <daxartio@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/daxartio/termynal"
homepage = "https://pypi.org/project/termynal"
keywords = []

[tool.poetry.plugins."mkdocs.plugins"]
"termynal" = "termynal.plugin:TermynalPlugin"

[tool.poetry.plugins."markdown.extensions"]
"termynal" = "termynal.markdown:TermynalExtension"

[tool.poetry.dependencies]
python = "^3.7"
markdown = "*"
mkdocs = {version = "*", optional = true}

[tool.poetry.dev-dependencies]
asynctest = "*"
autoflake = "*"
black = {version = "*", allow-prereleases = true}
flake8 = "*"
flake8-annotations-complexity = "*"
flake8-bandit = "*"
flake8-breakpoint = "*"
flake8-bugbear = "*"
flake8-builtins = "*"
flake8-comprehensions = "*"
flake8-eradicate = "*"
flake8-if-expr = "*"
flake8-isort = "*"
flake8-logging-format = "*"
flake8-print = "*"
flake8-pytest = "*"
flake8-pytest-style = "*"
flake8-requirements = "*"
flake8-return = "*"
git-changelog = "*"
mkdocs-material = "*"
mkdocstrings = "*"
mutmut = "*"
mypy = "*"
pep8-naming = "*"
pylint = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "*"
pytest-deadfixtures = "*"
pytest-mock = "*"
safety = "*"
toml = "*"
unify = "*"

[tool.poetry.extras]
mkdocs = ["mkdocs"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
