#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['ipywardley']

package_data = \
{'': ['*']}

extras_require = \
{'test': ['jupyterlab']}

setup(name='ipywardley',
      version='0.0.1',
      description='Wardley Map magic',
      author='Andrew N. Jackson',
      author_email='anj@anjackson.net',
      url='https://anjackson.net/',
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
     )
