
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f8ba460ef67a0c22d070c4e357c9ad81bc998908",
 "version": "0.14.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
