image: admin.reproducible.online/cc-base:7fad191
#image: admin.reproducible.online/cc-base:1fe5959

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - run

build: &job
  stage: build
#  image: admin.reproducible.online/cc-base:1fe5959
  services:
    - docker:stable-dind
  script:
    - build_deps
    - build
  only:
    - branches
  artifacts:
    paths:
    - "*.cwl"

run: 
  <<: *job
  stage: run
  script:
    - build_deps
    - run
  artifacts:
    paths:
    - "outputs/*"



# ---------------------------------------------------------------------------

.auto_devops: &auto_devops |
  # Auto DevOps variables and functions
  [[ "$TRACE" ]] && set -x
  export CI_APPLICATION_REPOSITORY=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
  export CI_APPLICATION_TAG=$CI_COMMIT_SHA
  export CI_CONTAINER_NAME=ci_job_build_${CI_JOB_ID}
  export TILLER_NAMESPACE=$KUBE_NAMESPACE
  export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')

  export PYTHONUNBUFFERED=1

  function build_deps() {
      apk add --update alpine-sdk \
                       python3 \
                       python3-dev \
                       build-base libffi-dev openssl-dev curl linux-headers zeromq-dev

      python3 -m ensurepip 

      if [ -s pip.conf ]; then
        cp -fv pip.conf /etc/pip.conf
      else
        touch pip.conf
      fi

  }

  function build() {
    make build
  }



  function run() {
        make run-one
  }

before_script:
  - *auto_devops
