# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csnews_multilingual', '0007_auto_20161129_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='csnews_multilingual.Article'),
        ),
        migrations.AlterField(
            model_name='photoextendedtranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='csnews_multilingual.PhotoExtended'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='csnews_multilingual.Tag'),
        ),
    ]
