# coding: utf-8

"""
    Camunda BPM REST API

    OpenApi Spec for Camunda BPM REST API.  # noqa: E501

    The version of the OpenAPI document: 7.14.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import generic_camunda_client
from generic_camunda_client.api.signal_api import SignalApi  # noqa: E501
from generic_camunda_client.rest import ApiException


class TestSignalApi(unittest.TestCase):
    """SignalApi unit test stubs"""

    def setUp(self):
        self.api = generic_camunda_client.api.signal_api.SignalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_throw_signal(self):
        """Test case for throw_signal

        """
        pass


if __name__ == '__main__':
    unittest.main()
