
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-13T14:43:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "382a1a24aa5350485c731644905cd8d43f11b3e3",
 "version": "1.14.2.post.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
