
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-18T21:54:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e25ed87b7cf8e06ea4e5faf20185989bb1313887",
 "version": "0.28.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
