apiVersion: v1
kind: ConfigMap
metadata:
  name: {(helm.name)}
data:
  {(app.module_name)}_config.yml: |
{{- if .Values.app.config.override }}
{{ toYaml .Values.app.config.override | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {(helm.name)}-env
data:
{{- if .Values.app.config.env }}
{{ toYaml .Values.app.config.env | indent 2 }}
{{- end }}
  "LOG_LEVEL": {{ .Values.app.config.log.level }}