apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {(helm.name)}
spec:
  replicas: {{ .Values.app.replicas }}
  template:
    metadata:
      labels:
        app: {(helm.name)}
        part-of: lm
    spec:
{{- if .Values.app.affinity }}
      affinity:
{{ toYaml .Values.app.affinity | indent 8 }}
{{- end }}
{{- if .Values.app.tolerations }}
      tolerations:
{{ toYaml .Values.app.tolerations | indent 8 }}
{{- end }}
      containers:
        - name: {(helm.name)}
          image: {{ .Values.docker.image }}:{{ .Values.docker.version }}
          imagePullPolicy: {{ .Values.docker.imagePullPolicy }}
          securityContext:
            # run as {(app.module_name)} user created in docker image
            runAsUser: 100
          ports:
          - containerPort: {(app.port)}
            protocol: TCP
          {{- if .Values.app.livenessProbe.enabled }}
          livenessProbe:
            failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
            httpGet:
              path: /management/health
              port: {(app.port)}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.app.readinessProbe.enabled }}
          readinessProbe:
            failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}
            httpGet:
              path: /management/health
              port: {(app.port)}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}         
          {{- end }}
          envFrom:
          - configMapRef:
              name: {(helm.name)}-env
          resources:
{{ toYaml .Values.app.resources | indent 12 }}   
          volumeMounts:
          - name: config
            mountPath: /var/{(app.module_name)}/{(app.module_name)}_config.yml
            subPath: {(app.module_name)}_config.yml
      volumes:
      - name: config
        configMap:
          name: {(helm.name)}
{{- if .Values.app.autoscaler.enabled }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {(helm.name)}
spec:
  maxReplicas: {{ .Values.app.autoscaler.maxReplicas }}
  minReplicas: {{ .Values.app.autoscaler.minReplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {(helm.name)}
  targetCPUUtilizationPercentage: {{ .Values.app.autoscaler.targetCPUUtilizationPercentage }}
{{- end }}
