{{- if .Values.ingress.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /  # This line is only needed when deploying on IBM Cloud Private.
  name: {(helm.name)}-ingress  # The ingress name must be unique for each ingress rule created.
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /  # This is the url path used to access the service externally.
        backend:
         serviceName: {(helm.name)}
         servicePort: {(app.port)}
{{- end }}