apiVersion: v1
kind: Service
metadata:
  name: {(helm.name)}
  labels:
    app: {(helm.name)}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {(app.port)}
    targetPort: {(app.port)}
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
    protocol: TCP
    name: http
  selector:
    app: {(helm.name)}
