# Autogenerated file. Do not modify
import typing

from .abstract import EiDatabase, EiDatabaseTable, EiDatabaseTableRow


class Quest(EiDatabaseTableRow):

    __slots__ = (
        "name",
        "experience",
        "unk2",
        "zone_number",
        "comment",
        "money",
        "record_number",
        "unk7",
    )

    def __init__(self):
        self.name: str = None
        self.experience: float = None
        self.unk2: int = None
        self.zone_number: int = None
        self.comment: str = None
        self.money: int = None
        self.record_number: int = None
        self.unk7: typing.List[str] = None
        super().__init__()

    @property
    def _db_type(self):
        return QuestsDatabase


class Briefing(EiDatabaseTableRow):

    __slots__ = (
        "name",
        "unk1",
        "money",
        "give_items",
        "comment",
        "take_items",
        "give_quests_1",
        "give_quests_2",
        "open_zones",
        "unk9",
        "bonus_number",
    )

    def __init__(self):
        self.name: str = None
        self.unk1: float = None
        self.money: float = None
        self.give_items: typing.List[str] = None
        self.comment: str = None
        self.take_items: typing.List[str] = None
        self.give_quests_1: typing.List[str] = None
        self.give_quests_2: typing.List[str] = None
        self.open_zones: typing.List[str] = None
        self.unk9: typing.List[str] = None
        self.bonus_number: int = None
        super().__init__()

    @property
    def _db_type(self):
        return QuestsDatabase


class Quests(EiDatabaseTable[Quest]):

    _row_type = Quest


class Briefings(EiDatabaseTable[Briefing]):

    _row_type = Briefing


class QuestsDatabase(EiDatabase):

    __slots__ = (
        "quests",
        "briefings",
    )

    def __init__(self):
        self.quests = Quests()
        self.briefings = Briefings()
        super().__init__()
