[tool.poetry]
authors = ["duyixian <duyixian1234@qq.com>"]
description = "Make automatically git commits when coding"
license = "MIT"
name = "auto-commit"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.3.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.6.4"
mypy = "^0.790"
pylint = "^2.6.0"

[tool.poetry.scripts]
auto-commit = "auto_commit.__main__:run"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
