[tool.poetry]
name = "zrtool"
version = "0.2.0"
description = "CLI tool to deal with ZoomR16 project"
authors = ["Rémy Taymans <remytms@tsmail.eu>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://gitlab.com/remytms/zrtool"
keywords = ["cli", "zoomr16", "audio", "recorder"]
classifiers = [
    "Intended Audience :: End Users/Desktop",
    "Development Status :: 3 - Alpha",
    "Operating System :: Unix",
    "Operating System :: POSIX",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Multimedia :: Sound/Audio",
]

[tool.poetry.scripts]
zrtool = "zrtool.cli:main"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"
invoke = "^1.3"
PyYAML = "^5.3"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
pylint = "*"
tox = "*"
toml = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79

[tool.towncrier]
package = "zrtool"
package_dir = "src"
filename = "CHANGES.rst"
directory = "newsfragments"
title_format = "zrtool {version} ({project_date})"
wrap = 72
