# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Sensor": "00_core.ipynb",
         "SensorWithValue": "00_core.ipynb",
         "Value": "00_core.ipynb",
         "License": "00_core.ipynb",
         "Settings": "00_core.ipynb",
         "retry_on": "00_core.ipynb",
         "generate_headers": "00_core.ipynb",
         "handle_response": "00_core.ipynb",
         "send_get": "00_core.ipynb",
         "send_post": "00_core.ipynb",
         "send_delete": "00_core.ipynb",
         "build_query": "00_core.ipynb",
         "login": "00_core.ipynb",
         "getSensors": "00_core.ipynb",
         "getSensor": "00_core.ipynb",
         "addSensor": "00_core.ipynb",
         "deleteSensor": "00_core.ipynb",
         "mySensors": "00_core.ipynb",
         "mySensorIds": "00_core.ipynb",
         "getFirstLastValueForSensor": "00_core.ipynb",
         "getValues": "00_core.ipynb",
         "getValuesForSensor": "00_core.ipynb",
         "addValue": "00_core.ipynb",
         "addMultipleValues": "00_core.ipynb",
         "profile": "00_core.ipynb",
         "getMeasurands": "00_core.ipynb",
         "getMeasurand": "00_core.ipynb",
         "getLicenses": "00_core.ipynb",
         "getLicense": "00_core.ipynb",
         "getUnits": "00_core.ipynb",
         "getUnit": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://flpeters.github.io/osnapi/"

git_url = "https://github.com/flpeters/osnapi/tree/master/"

def custom_doc_links(name): return None
