[tool.poetry]
name = "mobile-payments"
version = "0.1.0"
description = ""
authors = ["Innocent Zenda <zendainnocent@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.0"
pycryptodome = "^3.9.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
