name = 'pybk8500'
version = '1.1.5'
description = 'BK-8500-Electronic-Load python library'
url = 'https://github.com/justengel/pybk8500'
author = 'Justin Engel'
author_email = 'jtengel08@gmail.com'
