conda:
  image: continuumio/miniconda3:latest
  tags: 
  - linux

  script:
    - conda install mamba -c conda-forge
    - mamba env update -n fine --file=requirements.yml
    - mamba env update -n fine --file=requirements_dev.yml
    - mamba info --envs
    - source activate fine
    - python -m pip install -e .
    - python -m pytest --cov=FINE test/