
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0d68b1dc4476505eb132c5b482485928e605f0c5",
 "version": "4.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
