
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-16T18:13:05-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1e8f7d50824a7d3a2ea6f5d95603b1ac5c44f8b6",
 "version": "1.33.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
