
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-17T17:08:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf527d68e24051d313bfce741b5688cb11bbf7a1",
 "version": "0.1.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
