build: false
environment:
  global:
    TOXENV: py
  matrix:
    - PYVER: 27
    - PYVER: 36
    - PYVER: 37
    #- PYVER: 38
install:
  - git fetch --tags
  - C:\Python%PYVER%\scripts\pip install -U tox
test_script:
  - C:\Python%PYVER%\scripts\tox
cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '%USERPROFILE%\.cache\pre-commit'
