- id: reslate
  name: reslate
  description: "API documentation generator / updater."
  entry: reslate
  language: python
  language_version: python3
  always_run: true
  require_serial: true
  types: [python]
