language: python

python:
  - '3.8.6'
  - '3.9-dev'

jobs:
  include:
    - &stage_deploy
      stage: deploy test
      if: branch != main
      install:
        - pip install --upgrade pip
        - pip install twine build
      before_script:
        - python -m build .
        - twine check dist/*
      script:
        - twine upload --skip-existing --repository testpypi dist/*
      after_success: skip

    - <<: *stage_deploy
      stage: deploy prod
      if: branch = main AND type != pull_request
      script:
        - twine upload dist/*

install:
  - pip install --upgrade pip
  - pip install .[tests]

script:
  - flake8
  - black --diff --check .
  - mypy src
  - pytest --cov zmfcli --cov-report xml

after_success:
  - bash <(curl -s https://codecov.io/bash)