language: python

dist: xenial

python:
- '3.7'
- '3.8'

before_install:
  - pip install --upgrade pip

install:
  - pip install pytest
  - pip install mypy
  - pip install .

script:
  - pytest ./Lib/gftools/tests/test_usage.py
  - pytest ./Lib/gftools/tests/test_fix.py
  - mypy ./Lib/gftools/packager.py
