SUCCESS =   '[SUCCESS] '
SETTING =   '[SETTING] '
DEBUG =     '[DEBUG  ] '
WARNING =   '[WARNING] '
FAILURE =   '[FAILURE] '
WRAPPER =   '[WRAPPER] '
ERROR =     '[ERROR  ] '

NEW_LINE = '''\n'''
BAR_N = '''\\n'''
SPACE = ''' '''
NOTHING = ''''''
TRIPLE_SINGLE_QUOTE = """'''"""
TRIPLE_DOUBLE_QUOTE = '''"""'''
SINGLE_QUOTE = """'"""
DOUBLE_QUOTE = '''"'''
COMA = ''','''
COLON = ''':'''
BACK_SLASH = '''\\'''
SLASH = '''/'''
HASH_TAG = '''#'''
SPACE = ''' '''
DOT = '''.'''
DASH = '''-'''
SPACE_DASH_SPACE = ''' - '''
UNDERSCORE = '''_'''
DOT_SPACE = '''. '''
COMA_SPACE = ''', '''
COLON_SPACE = ''': '''
SPACE_COLON_SPACE = ''' : '''
LOG_CAUSE = f'''Cause{COLON_SPACE}'''
DOT_SPACE_CAUSE = f'''{DOT_SPACE}{LOG_CAUSE}'''

TAB_UNITS = 4
TAB = TAB_UNITS * SPACE

TRUE = 'True'
FALSE = 'False'

BOOLEAN = 'bool'
STRING = 'str'
INTEGER = 'int'
TUPLE = 'tuple'
LIST = 'list'
DICT = 'dict'

OPEN_TUPLE = '('
CLOSE_TUPLE = ')'
OPEN_LIST = '['
CLOSE_LIST = ']'
OPEN_DICTIONARY = '{'
CLOSE_DICTIONARY = '}'
LESSER = '<'
BIGGER = '>'

TYPE_FUNCTION = 'function'
TYPE_CLASS = 'class'
TYPE_BOOLEAN = 'bool'
TYPE_STRING = 'str'
TYPE_INTEGER = 'int'
TYPE_TUPLE = 'tuple'
TYPE_LIST = 'list'
TYPE_DICT = 'dict'

NULL_VALUE = 'null'
TRUE_VALUE = 'true'
FALSE_VALUE = 'false'
