
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-12T15:55:17+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4f22b9f2f32294d4f9f6f45f1e53b275239d0aed",
 "version": "0.1.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
