[tool.poetry]
name = "xpa"
version = "0.1.0"
description = "X-ray diffraction lib for analysis"
authors = ["Andre da Silva <andrezio@live.com>"]

[tool.poetry.dependencies]
python = ">=3.6.1,<4.0"
numpy = "^1.19.4"
pandas = "^1.1.4"
scipy = "^1.5.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
