[tool.poetry]
name = "cjk-commons"
version = "3.5.6"
description = "Commons"
authors = ["Cujoko <cujoko@gmail.com>"]
license = "MIT"
repository = "https://github.com/Cujoko/commons"
keywords = ["commons"]
classifiers=[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: Russian",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.9"
appdirs = "^1.4"
PyYAML = "^5.3"
yodl = "^1.0"
loguru = "^0.5"

[tool.poetry.dev-dependencies]
pylint = "^2.6"
pytest = "^6.1"
rope = "^0.18"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
