name: ldcpy
channels:
  - conda-forge
dependencies:
  - cartopy=0.18
  - codecov
  - netcdf4
  - pip
  - pytest
  - pytest-cov
  - xarray
  - zfpy
  - xrft
  - cmocean
  - dask
  - intake-esm
  - cython
  - nc-time-axis
  - scikit-image
  - opencv=4.2.0
  - matplotlib-base
