[tool]
[tool.poetry]
name = "sockio"
version = "0.5.1"
description = "Concurrency agnostic socket API"
license = "GPL-3.0-or-later"
keywords = ["socket", "asyncio"]
classifiers = ["Development Status :: 2 - Pre-Alpha", "Intended Audience :: Developers", "Natural Language :: English", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7"]
authors = ["Jose Tiago Macara Coutinho <coutinhotiago@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "*"
