name: Unit tests
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch

  push:
    branches:
      - master
  pull_request:
jobs:
  run:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python  
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Static code checking with pyflakes
      run: |
        pip install pytest 
        pip install pytest-cov
        pip install pyflakes
        pip install mypy
        pip install .
        pytest --cov=probatus/binning --cov=probatus/metric_volatility --cov=probatus/sample_similarity --cov=probatus/stat_tests --cov=probatus/utils --cov=probatus/interpret/ --ignore==tests/interpret/test_inspector.py --cov-report term-missing
        pyflakes probatus
        mypy probatus --ignore-missing-imports