
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "139924a51d45a0a229e964f62ea8dd3f72a089ca",
 "version": "7.6.2pre5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
