from wx import PyEventBinder, Bitmap

# Based on wxPython
# Copyright: (c) 2018 by Total Control Software
# License:   wxWindows License


def dummy_function(*args, **kwargs):
	return 0


AEDIALOG_STYLE = 536877141
class ArrayPGProperty: ...
class ArrayStringProperty: ...
class BoolProperty: ...
class ColourProperty: ...
class ColourPropertyValue: ...
class CursorProperty: ...
class DateProperty: ...
class DirProperty: ...
class EditEnumProperty: ...
class EditorDialogProperty: ...
class EnumProperty: ...
class FileProperty: ...
class FlagsProperty: ...
class FloatProperty: ...
class FontProperty: ...
class ImageFileProperty: ...
class IntProperty: ...
class LongStringProperty: ...
class MultiChoiceProperty: ...
NullProperty = None
class NumericProperty: ...
class NumericPropertyValidator: ...
class PGArrayEditorDialog: ...
class PGArrayStringEditorDialog: ...
class PGAttributeStorage: ...
class PGCell: ...
class PGCellData: ...
class PGCellRenderer: ...
class PGCheckBoxEditor: ...
class PGChoiceAndButtonEditor: ...
class PGChoiceEditor: ...
class PGChoiceEntry: ...
class PGChoices: ...
class PGChoicesData: ...
PGChoicesEmptyData = None
class PGComboBoxEditor: ...
class PGDefaultRenderer: ...
class PGEditor: ...
class PGEditorDialogAdapter: ...
PGGetDefaultImageWildcard = dummy_function
class PGInDialogValidator: ...
PGMAN_DEFAULT_STYLE = 0
class PGMultiButton: ...
class PGNumericValidationConstants: ...
class PGPaintData: ...
class PGPropArgCls: ...
class PGProperty: ...
class PGPropertyFlags: ...
class PGSpinCtrlEditor: ...
class PGTextCtrlAndButtonEditor: ...
class PGTextCtrlEditor: ...
class PGVIterator: ...
class PGValidationInfo: ...
class PGWindowList: ...
PG_ACTION_CANCEL_EDIT = 5
PG_ACTION_COLLAPSE_PROPERTY = 4
PG_ACTION_EDIT = 6
PG_ACTION_EXPAND_PROPERTY = 3
PG_ACTION_INVALID = 0
PG_ACTION_MAX = 8
PG_ACTION_NEXT_PROPERTY = 1
PG_ACTION_PRESS_BUTTON = 7
PG_ACTION_PREV_PROPERTY = 2
PG_ALPHABETIC_MODE = 48
PG_ARRAY_DELIMITER = 'Delimiter'
PG_ATTR_AUTOCOMPLETE = 'AutoComplete'
PG_ATTR_DEFAULT_VALUE = 'DefaultValue'
PG_ATTR_HINT = 'Hint'
PG_ATTR_INLINE_HELP = 'Hint'
PG_ATTR_MAX = 'Max'
PG_ATTR_MIN = 'Min'
PG_ATTR_MULTICHOICE_USERSTRINGMODE = 'UserStringMode'
PG_ATTR_SPINCTRL_MOTION = 'MotionSpin'
PG_ATTR_SPINCTRL_MOTIONSPIN = 'MotionSpin'
PG_ATTR_SPINCTRL_STEP = 'Step'
PG_ATTR_SPINCTRL_WRAP = 'Wrap'
PG_ATTR_UNITS = 'Units'
PG_AUTO_SORT = 16
PG_BASE_DEC = 10
PG_BASE_HEX = 16
PG_BASE_HEXL = 32
PG_BASE_OCT = 8
PG_BOLD_MODIFIED = 64
PG_BOOL_USE_CHECKBOX = 'UseCheckbox'
PG_BOOL_USE_DOUBLE_CLICK_CYCLING = 'UseDClickCycling'
PG_COLOUR_ALLOW_CUSTOM = 'AllowCustom'
PG_COLOUR_BLACK = (-1, -1, -1, 255)
PG_COLOUR_CUSTOM = 16777215
PG_COLOUR_HAS_ALPHA = 'HasAlpha'
PG_COLOUR_UNSPECIFIED = 16777216
PG_COLOUR_WEB_BASE = 65536
PG_COMPOSITE_FRAGMENT = 16
PG_DATE_FORMAT = 'DateFormat'
PG_DATE_PICKER_STYLE = 'PickerStyle'
PG_DEFAULT_IMAGE_SIZE = (-1, -1)
PG_DEFAULT_STYLE = 0
PG_DESCRIPTION = 8192
PG_DIALOG_TITLE = 'DialogTitle'
PG_DIR_DIALOG_MESSAGE = 'DialogMessage'
PG_DONT_RECURSE = 0
PG_EDITABLE_VALUE = 8
PG_EX_ALWAYS_ALLOW_FOCUS = 1048576
PG_EX_AUTO_UNSPECIFIED_VALUES = 2097152
PG_EX_ENABLE_TLP_TRACKING = 67108864
PG_EX_HELP_AS_TOOLTIPS = 65536
PG_EX_HIDE_PAGE_BUTTONS = 16777216
PG_EX_INIT_NOCAT = 4096
PG_EX_MODE_BUTTONS = 32768
PG_EX_MULTIPLE_SELECTION = 33554432
PG_EX_NATIVE_DOUBLE_BUFFERING = 524288
PG_EX_NO_FLAT_TOOLBAR = 8192
PG_EX_NO_TOOLBAR_DIVIDER = 134217728
PG_EX_TOOLBAR_SEPARATOR = 268435456
PG_EX_WINDOW_PGMAN_STYLE_MASK = 419471360
PG_EX_WINDOW_PG_STYLE_MASK = 108597248
class PG_EX_WINDOW_STYLES: ...
PG_EX_WINDOW_STYLE_MASK = 528068608
PG_EX_WRITEONLY_BUILTIN_ATTRIBUTES = 4194304
PG_FILE_DIALOG_STYLE = 'DialogStyle'
PG_FILE_DIALOG_TITLE = 'DialogTitle'
PG_FILE_INITIAL_PATH = 'InitialPath'
PG_FILE_SHOW_FULL_PATH = 'ShowFullPath'
PG_FILE_SHOW_RELATIVE_PATH = 'ShowRelativePath'
PG_FILE_WILDCARD = 'Wildcard'
PG_FLOAT_PRECISION = 'Precision'
PG_FORCE = 256
PG_FULL_VALUE = 1
class PG_GETPROPERTYVALUES_FLAGS: ...
PG_HIDE_CATEGORIES = 32
PG_HIDE_MARGIN = 512
PG_INC_ATTRIBUTES = 64
PG_INVALID_VALUE = 2147483647
PG_ITERATE_ALL = 1679848484
PG_ITERATE_ALL_PARENTS = 25600
PG_ITERATE_ALL_PARENTS_RECURSIVELY = 1677747200
PG_ITERATE_CATEGORIES = 536879136
PG_ITERATE_DEFAULT = 1612731428
PG_ITERATE_FIXED_CHILDREN = 1677743136
PG_ITERATE_HIDDEN = 2097156
PG_ITERATE_NORMAL = 1612731428
PG_ITERATE_PROPERTIES = 1610634272
PG_ITERATE_VISIBLE = 1677751328
class PG_ITERATOR_FLAGS: ...
PG_ITERATOR_FLAGS_ALL = 29732
PG_ITERATOR_MASK_OP_ITEM = 29732
PG_ITERATOR_MASK_OP_PARENT = 29732
PG_KEEP_STRUCTURE = 16
class PG_KEYBOARD_ACTIONS: ...
PG_LABEL = '@!'
PG_LABEL_STRING = '@!'
PG_LIMITED_EDITING = 2048
class PG_MISC_ARG_FLAGS: ...
PG_NO_INTERNAL_BORDER = 16384
PG_PREFIX_0x = 1
PG_PREFIX_DOLLAR_SIGN = 2
PG_PREFIX_NONE = 0
PG_PROGRAMMATIC_VALUE = 128
PG_PROPERTY_SPECIFIC = 4
PG_PROPERTY_VALIDATION_ERROR_MESSAGE = 0
PG_PROPERTY_VALIDATION_SATURATE = 1
PG_PROPERTY_VALIDATION_WRAP = 2
PG_PROP_ACTIVE_BTN = 524288
PG_PROP_AGGREGATE = 1024
PG_PROP_AUTO_UNSPECIFIED = 262144
PG_PROP_BEING_DELETED = 2097152
PG_PROP_CATEGORY = 8192
PG_PROP_CHILDREN_ARE_COPIES = 2048
PG_PROP_CLASS_SPECIFIC_1 = 524288
PG_PROP_CLASS_SPECIFIC_2 = 1048576
PG_PROP_COLLAPSED = 32
PG_PROP_COMPOSED_VALUE = 65536
PG_PROP_CUSTOMIMAGE = 8
PG_PROP_DISABLED = 2
PG_PROP_HIDDEN = 4
PG_PROP_INVALID_VALUE = 64
PG_PROP_MAX = 262144
PG_PROP_MISC_PARENT = 16384
PG_PROP_MODIFIED = 1
PG_PROP_NOEDITOR = 16
PG_PROP_PARENTAL_FLAGS = 25600
PG_PROP_PASSWORD = 1048576
PG_PROP_PROPERTY = 4096
PG_PROP_READONLY = 32768
PG_PROP_SHOW_FULL_FILENAME = 524288
PG_PROP_STATIC_CHOICES = 524288
PG_PROP_TRANSLATE_CUSTOM = 524288
PG_PROP_USES_COMMON_VALUE = 131072
PG_PROP_USE_CHECKBOX = 524288
PG_PROP_USE_DCC = 1048576
PG_PROP_WAS_MODIFIED = 512
PG_RECURSE = 32
PG_RECURSE_STARTS = 128
PG_REPORT_ERROR = 2
class PG_SETVALUE_FLAGS: ...
PG_SETVAL_AGGREGATED = 2
PG_SETVAL_BY_USER = 8
PG_SETVAL_FROM_PARENT = 4
PG_SETVAL_REFRESH_EDITOR = 1
PG_SORT_TOP_LEVEL_ONLY = 512
PG_SPLITTER_AUTO_CENTER = 128
PG_STATIC_LAYOUT = 1536
PG_STATIC_SPLITTER = 1024
PG_STRING_PASSWORD = 'Password'
PG_STRING_STORED_FLAGS = 54
PG_TOOLBAR = 4096
PG_TOOLTIPS = 256
PG_UINT_BASE = 'Base'
PG_UINT_PREFIX = 'Prefix'
PG_UNEDITABLE_COMPOSITE_FRAGMENT = 32
class PG_VALIDATION_FAILURE_BEHAVIOR_FLAGS: ...
PG_VALUE_IS_CURRENT = 64
PG_VFB_BEEP = 2
PG_VFB_DEFAULT = 20
PG_VFB_MARK_CELL = 4
PG_VFB_SHOW_MESSAGE = 8
PG_VFB_SHOW_MESSAGEBOX = 16
PG_VFB_SHOW_MESSAGE_ON_STATUSBAR = 32
PG_VFB_STAY_IN_PROPERTY = 1
class PG_WINDOW_STYLES: ...
PG_WINDOW_STYLE_MASK = 32752
class PropertyCategory: ...
class PropertyGrid: ...
class PropertyGridEvent: ...
class PropertyGridHitTestResult: ...
class PropertyGridInterface: ...
class PropertyGridIterator: ...
class PropertyGridIteratorBase: ...
class PropertyGridManager: ...
PropertyGridManagerNameStr = b'wxPropertyGridManager'
PropertyGridNameStr = b'wxPropertyGrid'
class PropertyGridPage: ...
class PropertyGridPageState: ...
class PropertyGridPopulator: ...
class PyArrayStringProperty: ...
class PyChoiceEditor: ...
class PyColourProperty: ...
class PyComboBoxEditor: ...
class PyEditEnumProperty: ...
class PyEditor: ...
class PyEditorDialogAdapter: ...
class PyEnumProperty: ...
class PyFileProperty: ...
class PyFlagsProperty: ...
class PyFloatProperty: ...
class PyFontProperty: ...
class PyIntProperty: ...
class PyLongStringProperty: ...
class PyProperty: ...
class PyStringProperty: ...
class PySystemColourProperty: ...
class PyTextCtrlEditor: ...
class PyUIntProperty: ...
RegisterEditor = dummy_function
class StringProperty: ...
class SystemColourProperty: ...
class UIntProperty: ...
_PropertyGridManager__init__ = dummy_function
_PropertyGrid__init__ = dummy_function
_type2property = None
_vt2getter = None
testPGVariantTypeName = dummy_function
testPGVariantTypemap = dummy_function
wxEVT_PG_CHANGED = 10459
wxEVT_PG_CHANGING = 10458
wxEVT_PG_COL_BEGIN_DRAG = 10468
wxEVT_PG_COL_DRAGGING = 10469
wxEVT_PG_COL_END_DRAG = 10470
wxEVT_PG_DOUBLE_CLICK = 10465
wxEVT_PG_HIGHLIGHTED = 10460
wxEVT_PG_ITEM_COLLAPSED = 10464
wxEVT_PG_ITEM_EXPANDED = 10463
wxEVT_PG_LABEL_EDIT_BEGIN = 10466
wxEVT_PG_LABEL_EDIT_ENDING = 10467
wxEVT_PG_PAGE_CHANGED = 10462
wxEVT_PG_RIGHT_CLICK = 10461
wxEVT_PG_SELECTED = 10457
EVT_PG_CHANGED = PyEventBinder()
EVT_PG_CHANGING = PyEventBinder()
EVT_PG_COL_BEGIN_DRAG = PyEventBinder()
EVT_PG_COL_DRAGGING = PyEventBinder()
EVT_PG_COL_END_DRAG = PyEventBinder()
EVT_PG_DOUBLE_CLICK = PyEventBinder()
EVT_PG_HIGHLIGHTED = PyEventBinder()
EVT_PG_ITEM_COLLAPSED = PyEventBinder()
EVT_PG_ITEM_EXPANDED = PyEventBinder()
EVT_PG_LABEL_EDIT_BEGIN = PyEventBinder()
EVT_PG_LABEL_EDIT_ENDING = PyEventBinder()
EVT_PG_PAGE_CHANGED = PyEventBinder()
EVT_PG_RIGHT_CLICK = PyEventBinder()
EVT_PG_SELECTED = PyEventBinder()
PGEditor_CheckBox = PGEditor()
PGEditor_Choice = PGEditor()
PGEditor_ChoiceAndButton = PGEditor()
PGEditor_ComboBox = PGEditor()
PGEditor_DatePickerCtrl = PGEditor()
PGEditor_SpinCtrl = PGEditor()
PGEditor_TextCtrl = PGEditor()
PGEditor_TextCtrlAndButton = PGEditor()
PG_NULL_BITMAP = Bitmap()
