general:
    backend: pytorch

pipeline: [fullytrain]

fullytrain:
    pipe_step:
        type: FullyTrainPipeStep

    model:
        model_desc:
            modules: ['Detector']
            Detector:
                type: FasterRCNN
                num_classes: 91
                backbone:
                    type: ResNetDet
                    depth: 18
                neck:
                    type: FPN
    trainer:
        type: Trainer
        get_train_metric_after_epoch: False
        model_statistics: False
        is_detection_trainer: True
        epochs: 20
        optimizer:
            type: SGD
            params:
                lr: 0.06
                momentum: 0.9
                weight_decay: 0.0001
        lr_scheduler:
            type: WarmupScheduler
            params:
                by_epoch: False
                warmup_type: linear
                warmup_iters: 2000
                warmup_ratio: 0.1
                after_scheduler_config:
                    type: CosineAnnealingLR
                    T_max: 30000
                    eta_min: 0.0001
                after_scheduler_by_epoch: False
        loss:
            type: SumLoss
        metric:
            type: coco
            params:
                anno_path: /cache/datasets/COCO2017/annotations/instances_val2017.json

    dataset:
        type: CocoDataset
        common:
            batch_size: 1
            data_root: /cache/datasets/COCO2017/
            img_prefix: 2017
            ann_prefix: instances
            transforms:
                -   type: PolysToMaskTransform
                -   type: PILToTensor
