# {{ managed_message }}
---

language: python
dist: {{ travis_ubuntu_version }}
cache: pip
python:
  {% for version in python_versions %}- '{{ version }}'
  {% endfor %}
install:
  {% for line in travis_extra_install_pre %}- {{ line }}
  {% endfor %}
  - pip install --upgrade pip {% for req in travis_additional_requirements %}{{ req }} {% endfor %}
  - pip install tox
  {% for line in travis_extra_install_post %}- {{ line }}
  {% endfor %}

script:
  - tox -e mypy,build

stages:
  - mypy
  - build
{% if enable_conda %}  - deploy_conda{% endif %}

jobs:
  include:
    - stage: mypy
      python: "{{ min_py_version }}"
      script:
        - tox -e mypy

    - stage: build
      script:
        - tox -e build
{% if enable_conda %}    - stage: deploy_conda
      python: "{{ python_deploy_version }}"
      addons:
        apt:
          update: true
      install:
        - pip install rst2txt yolk3k
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - chmod +x .ci/travis_deploy_conda.sh
      script: skip
      deploy:
        on:
          repo: {{ username }}/{{ repo_name }}
        provider: script
        script: .ci/travis_deploy_conda.sh || return 1;{% endif %}
