
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-11T10:07:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4997b23466178e87b2cd753e10d8c8f89565bd6a",
 "version": "1.0.3.1b5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
