[tool.black]
line-length = 120
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

# Black compatible config from https://black.readthedocs.io/en/stable/compatible_configs.html
[tool.isort]
profile = "black"
