[tool.flit.metadata]
module = "pyhstr"
author = "adder46"
author-email = "dedmauz69@gmail.com"
home-page = "https://github.com/adder46/pyhstr"
description-file = "README.md"
requires-python = ">=3.6"
keywords = "python history shell extension"
requires = []
dist-name = "pyhstr"

