
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-14T13:26:00-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b8b3c268695431de65af954c3d1211d11a4fef2",
 "version": "0.7.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
