
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-17T11:48:38-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f11c1cc442043e73ece6153d0fc4c92f7bd02855",
 "version": "2.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
