[tool.poetry]
name = "click-inspect"
version = "0.2"
description = "Add options to click commands based on inspecting functions"
authors = ["Dominik1123"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Dominik1123/click-inspect"
repository = "https://github.com/Dominik1123/click-inspect"
keywords = ["click", "command line interface", "inspect"]

[tool.poetry.dependencies]
python = "^3.7.9"
importlib_metadata = {version = "^1.6.1", python = "<3.8"}
typing-extensions = {version = "^3.7.4.3", python = "<3.9"}
click = "^7.1.2"
Sphinx = "^3.3.0"
typestring-parser = "^0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
coverage = {extras = ["toml"], version = "^5.1"}
pytest-cov = "^2.9.0"
flake8 = "^3.8.3"
black = "^19.10b0"
flake8-black = "^0.2.0"
mypy = "^0.780"
flake8-docstrings = "^1.5.0"
darglint = "^1.4.1"
codecov = "^2.1.4"

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["click_inspect"]
omit = ["src/click_inspect/__init__.py"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
