[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "gitprovenance"
author = "Pauli Virtanen"
author-email = "pav@iki.fi"
home-page = "https://github.com/pv/gitprovenance/"
requires = []
requires-python = ">=3.5"
