[tool.poetry]
name = "pymedphys"
version = "0.35.0-dev1"
readme = "README.rst"
description = "Medical Physics library"
authors = [
    "PyMedPhys Contributors <developers@pymedphys.com>",
    "Simon Biggs <sbiggs@pymedphys.com>",
    "Matthew Jennings <mjennings@pymedphys.com>",
    "Stuart Swerdloff",
    "Phillip Chlap",
    "Jake Rembish",
    "Matthew Cooper <mcooper@pymedphys.com>",
    "Jacob McAloney",
    "Pedro Martinez"
]
license = "Apache-2.0"
homepage = "https://pymedphys.com"
repository = "https://github.com/pymedphys/pymedphys"
documentation = "https://docs.pymedphys.com"
classifiers = [
    "Development Status :: 4 - Beta",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Scientific/Engineering :: Physics",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
]

packages = [{include = "pymedphys", from = "lib" }]

[tool.poetry.dependencies]
python = "^3.6"
dataclasses = {version = "*", python = "~3.6"}

# library
tqdm = {version = "*", optional = true}  # groups = ["user", "dev"]
attrs = {version = "*", optional = true}  # groups = ["user", "dev"]
watchdog = {version = "*", optional = true}  # groups = ["user", "dev"]

keyring = {version = "*", optional = true}  # groups = ["user", "dev"]
packaging = {version = "*", optional = true}  # groups = ["user", "dev"]
PyYAML = {version = "*", optional = true}  # groups = ["user", "dev"]
requests = {version = "*", optional = true}  # groups = ["user", "dev"]

numpy = {version = ">= 1.12", optional = true}  # groups = ["user", "dev"]
matplotlib = {version = "*", optional = true}  # groups = ["user", "dev"]
scipy = {version = "*", optional = true}  # groups = ["user", "dev"]
pandas = {version = "*", optional = true}  # groups = ["user", "dev"]

Pillow = {version = "*", optional = true}  # groups = ["user", "dev"]
imageio = {version = "*", optional = true}  # groups = ["user", "dev"]

shapely = {version = ">= 1.7.0", optional = true}  # groups = ["user", "dev"]

dbfread = {version = "*", optional = true}  # groups = ["user", "dev"]

pydicom = {version = ">=2.0.0", optional = true}  # groups = ["user", "dev", "dicom"]
pynetdicom = {version = "*", optional = true}  # groups = ["user", "dev", "dicom"]
pylibjpeg-libjpeg = {version = "*", optional = true}  # groups = ["user", "dev", "dicom"]
immutables = {version = "*", optional = true}  # groups = ["user", "dev", "dicom"]

cython = {version = "*", optional = true}  # groups = ["user", "dev"]
pymssql = {version = "*", optional = true}  # groups = ["user", "dev"]

kiwisolver = {version = "!=1.3.0", optional = true}  # groups = ["user", "dev"]
xmltodict = {version = "*", optional = true}  # groups = ["user", "dev"]
pylinac = {version = "2.3.2", optional = true}  # groups = ["user", "dev"]

# used within experimental modules
python_dateutil = {version = "*", optional = true}  # groups = ["user", "dev", "experimental"]
scikit-image = {version = "*", optional = true}  # groups = ["user", "dev", "experimental"]

# gui
streamlit = {version = "0.70.0", optional = true}  # groups = ["user", "dev", "gui"]
timeago = {version = "*", optional = true}  # groups = ["user", "dev", "gui"]

# ml
tensorflow = {version = ">=2.2.0", optional = true}  # groups = ["ml", "doctests"]
torch = {version = ">=1.0.0", optional = true}  # groups = ["ml"]

# docs
sphinx = {version = ">= 1.4, < 1.8", optional = true}  # groups = ["dev", "docs"]
sphinx-rtd-theme  = {version = "^0.4.3", optional = true}  # groups = ["dev", "docs"]
sphinxcontrib-napoleon = {version = "*", optional = true}  # groups = ["dev", "docs"]
sphinx-argparse = {version = "*", optional = true}  # groups = ["dev", "docs"]
sphinx-autobuild = {version = "*", optional = true}  # groups = ["dev", "docs"]
nbsphinx  = {version = "*", optional = true}  # groups = ["dev", "docs"]
jupyter_client = {version = "*", optional = true}  # groups = ["dev", "docs"]
ipython = {version = "*", optional = true}  # groups = ["dev", "docs"]
ipykernel = {version = "*", optional = true}  # groups = ["dev", "docs"]
nbconvert = {version = "6.0.6", optional = true}  # groups = ["dev", "docs"]

# tests
pytest = {version = "*", optional = true}  # groups = ["dev", "tests"]
pytest-sugar  = {version = "*", optional = true}  # groups = ["dev", "tests"]
hypothesis  = {version = "*", optional = true}  # groups = ["dev", "tests"]
psutil  = {version = "*", optional = true}  # groups = ["dev", "tests"]
pylint  = {version = "*", optional = true}  # groups = ["dev", "tests"]
pytest-pylint  = {version = "*", optional = true}  # groups = ["dev", "tests"]

# dev
pre-commit = {version = "*", optional = true}  # groups = ["dev"]
black = {version = "^19.3b0", optional = true}  # groups = ["dev", "doctests"]
mypy = {version = "*", optional = true}  # groups = ["dev"]
rope = {version = "*", optional = true}  # groups = ["dev"]
doc8 = {version = "*", optional = true}  # groups = ["dev"]
tomlkit = {version = "*", optional = true}  # groups = ["dev", "doctests"]
readme-renderer = {version = "*", optional = true}  # groups = ["dev"]


[tool.poetry.extras]
user = ["tqdm", "attrs", "watchdog", "keyring", "packaging", "PyYAML", "requests", "numpy", "matplotlib", "scipy", "pandas", "Pillow", "imageio", "shapely", "dbfread", "pydicom", "pynetdicom", "pylibjpeg-libjpeg", "immutables", "cython", "pymssql", "kiwisolver", "xmltodict", "pylinac", "python_dateutil", "scikit-image", "streamlit", "timeago"]
dev = ["tqdm", "attrs", "watchdog", "keyring", "packaging", "PyYAML", "requests", "numpy", "matplotlib", "scipy", "pandas", "Pillow", "imageio", "shapely", "dbfread", "pydicom", "pynetdicom", "pylibjpeg-libjpeg", "immutables", "cython", "pymssql", "kiwisolver", "xmltodict", "pylinac", "python_dateutil", "scikit-image", "streamlit", "timeago", "sphinx", "sphinx-rtd-theme", "sphinxcontrib-napoleon", "sphinx-argparse", "sphinx-autobuild", "nbsphinx", "jupyter_client", "ipython", "ipykernel", "nbconvert", "pytest", "pytest-sugar", "hypothesis", "psutil", "pylint", "pytest-pylint", "pre-commit", "black", "mypy", "rope", "doc8", "tomlkit", "readme-renderer"]
dicom = ["pydicom", "pynetdicom", "pylibjpeg-libjpeg", "immutables"]
experimental = ["python_dateutil", "scikit-image"]
gui = ["streamlit", "timeago"]
ml = ["tensorflow", "torch"]
doctests = ["tensorflow", "black", "tomlkit"]
docs = ["sphinx", "sphinx-rtd-theme", "sphinxcontrib-napoleon", "sphinx-argparse", "sphinx-autobuild", "nbsphinx", "jupyter_client", "ipython", "ipykernel", "nbconvert"]
tests = ["pytest", "pytest-sugar", "hypothesis", "psutil", "pylint", "pytest-pylint"]

[tool.poetry.scripts]
pymedphys = "pymedphys.__main__:main"

[tool.isort]
multi_line_output = 3
line_length = 88
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

known_third_party = [
    "pymedphys._imports"
]
known_general_scientific = [
    "numpy", "scipy", "pandas", "imageio", "PIL", "skimage", "matplotlib",
    "mpl_toolkits", "shapely"
]
known_machine_learning = [
    "tensorflow", "streamlit"
]
known_medphys = [
    "pydicom", "pylinac", "pynetdicom", "libjpeg"
]
known_first_party = ["pymedphys"]
sections = [
    "FUTURE", "STDLIB", "THIRDPARTY", "GENERAL_SCIENTIFIC", "MACHINE_LEARNING",
    "MEDPHYS", "FIRSTPARTY", "LOCALFOLDER"
]

[build-system]
requires = ["poetry >= 1.0.9", "setuptools >= 42.0.0", "wheel >= 0.29.0"]
build-backend = "poetry.masonry.api"
