[tool.poetry]
name = "pymathalgos"
version = "0000000000000000000000"
description = ""
authors = ["Adi58816 <adisalimgereev@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
