[tool.poetry]
name = "pyqalx"
version = "0.14.2"
description = "High-level interfaces to the qalx API"
authors = ["AgileTek Engineering Limited <london@agiletek.co.uk>"]
classifiers=[
          'Programming Language :: Python :: 3.6',
          'Programming Language :: Python :: 3.7',
          'Development Status :: 4 - Beta',
          'Intended Audience :: Manufacturing',
          'Intended Audience :: Science/Research',
          'Intended Audience :: Telecommunications Industry',
          'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
          'Natural Language :: English',
          'Operating System :: OS Independent'
      ]
keywords=['qalx', 'engineering', 'simulation']
license='GPL-3.0'
packages = [
                { include = "qalxcli" },
                { include = 'pyqalx/**/*.py'}
    ]
readme="README.rst"
homepage="https://qalx.net"
documentation="https://docs.qalx.net"


[tool.poetry.scripts]
qalx = "qalxcli.cli.qalx:qalx"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.21"
boto3 = "^1.12.31"
dill = ">=0.3.3"
click = "^7.0"
jsonschema = "^3.0"
deprecation = "^2.0"
flaky = {version = "^3.5",optional = true}
sphinx = {version = "^2.0",optional = true}
pip-licenses = {version = "^1.16",optional = true}
tabulate = "^0.8.6"
appdirs = "^1.4"
pyyaml = "^5.3"
gitpython = "^3.1"
troposphere = "^2.6"
treelib = "^1.6"
colorama = "^0.4.3"
cryptography = "^2.9"
bson_extra = "^0.0.3"
addict = "^2.2"

[tool.poetry.extras]
sphinx = ["sphinx"]
flaky = ["flaky"]
pip-licenses = ["pip-licenses"]


[tool.poetry.dev-dependencies]
pytest = "^4.4"
pytest-mock = "^1.10"
pytest-xdist = "^1.28"
pre-commit = "^1.20"
pytest-cov = "^2.8"
pytest-timeout = "^1.3"


[tool.black]
line-length = 80

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

