language: python
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -U pip
  - pip install -r ./tests/requirements.txt
  - pip install .
# command to run tests
script:
  - pytest
after_success:
  - coveralls
