[tool.black]
line-length = 120
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
|tests/protobuf3_models_tests_pb2.py
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
skip_glob = '*_pb2.py'
known_first_party = 'protobuf3_models'
indent = '    '
combine_as_imports = true

[tool.pytest.ini_options]
addopts = '--capture=no --verbose --html=htmltest/report.html --self-contained-html --junit-xml=report.xml --cov=. --cov-report=html --cov-report=xml'

[tool.coverage.run]
omit = [
    '*/__init__.py',
    'setup.py',
    '*/tests/*',
    '*/.eggs/*',
    'setup_commands/*',
]

[tool.coverage.report]
exclude_lines = [
    'pragma: no cover',
    'raise AssertionError',
    'raise NotImplementedError',
    'return NotImplemented',
    'if 0:',
    'if __name__ == .__main__.:',
]
