name: CI
on:
    push:
        branches: [ '**' ]
    pull_request:
        paths-ignore:
        - 'doc/*.rst'
    schedule:
        - cron:  '17 3 * * 0'

jobs:
    flake8:
        name: Flake8
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -
            uses: actions/setup-python@v1
            with:
                python-version: 3.8
        -   name: "Main Script"
            run: |
                pip install flake8 matplotlib
                flake8 pydemic test/*.py examples/*.py
    pylint:
        name: Pylint
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -
            uses: actions/setup-python@v1
            with:
                python-version: 3.8
        -   name: "Main Script"
            run: |
                python setup.py develop
                pip install pylint pytest matplotlib
                pylint --rcfile=setup.cfg pydemic test/test_*.py examples/*.py
    pytest:
        name: Pytest
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -
            uses: actions/setup-python@v1
            with:
                python-version: 3.8
        -   name: "Main Script"
            run: |
                python setup.py develop
                pip install pytest
                pytest
