language: python
python:
   - 3.6
   - 3.7
   - 3.8

install:
    - pip install -e .[tests]

script:
    - coverage run -m pytest -s -v
    #- py.test tests/run_tests.py

after_success:
   - coveralls

notifications:
   email: false
