dist: xenial   # required for Python >= 3.7

sudo: false

language: python

services:
  - docker

cache: pip

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  # Disable "nightly" for now due to psycopg2cffi build failures because of python-3.10-dev
  # - "nightly"  # nightly build
  - "pypy3.5"  # Pypy3 3.5.3

before_script:
  - docker-compose -f tests/docker-compose.yml up -d
  - sleep 15

install:
  - make deps

script:
  # All default tests with in-memory storage
  - make coverage MARK='"not integration"' COVERAGE_OPTS="--cov-append"
  # MongoDB storage integration tests
  - MONGODB_HOST="mongodb://mongo:password@localhost:27017" make coverage MARK='"mongo"' COVERAGE_OPTS="--cov-append"
  # MySQL storage integration tests
  - SQL_HOST="mysql+pymysql://mysql:password@localhost/py_abac" make coverage MARK='"sql"' COVERAGE_OPTS="--cov-append"
  # Postgres storage integration tests
  - SQL_HOST="postgresql+psycopg2cffi://postgres:password@localhost/py_abac" make coverage MARK='"sql"' COVERAGE_OPTS="--cov-append"
  # Redis storage integration tests
  - REDIS_HOST="localhost" REDIS_PORT="6379" make coverage MARK='"redis"' COVERAGE_OPTS="--cov-append"
  # File storage integration tests
  - make coverage MARK='"file"' COVERAGE_OPTS="--cov-append"

after_success:
  - bash <(curl -s https://codecov.io/bash)
