[tool.poetry]
name = "django-mongoengine"
version = "0.4.4"
description = "Django support for MongoDB via MongoEngine"
authors = ["Ross Lawley <ross.lawley@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7"
django = "~3"
mongoengine = ">=0.14"

[tool.poetry.dev-dependencies]
sphinx = "*"
nose = "*"
coverage = "*"
flake8 = "^3.7.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
