[tool.poetry]
name = "ream"
version = "0.1.3.4"
description = "parser/dumper for REAM files"
authors = ["Chih-Ming Louis Lee <louis@chihminglee.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/chmlee/ream-python"
classifiers = [
    "Topic :: Scientific/Engineering",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 3 - Alpha"
]

packages = [
  {include = "ream"}
]

[tool.poetry.dependencies]
python = "^3.8"
lark-parser = "^0.11.1"
pandas = "^1.1.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ream = "ream.commandline:main"
