dist: bionic
language: python
cache:
  - pip
  - apt
python:
  - '3.6'
  - '3.7'
  - '3.8'
services:
  - postgresql
addons:
  postgresql: '10'
  apt:
    packages:
      - python3-enchant
      - graphviz
      - postgresql-10-postgis-2.5
install:
  - pip install tox-travis
  - pip install -U codecov
before_script:
  - psql template1 -c "create extension postgis;"
  - createdb heroku_connect_test
script:
  - tox -v
after_success:
  - codecov
stages:
- test
- name: deploy
  if: repo = Thermondo/django-heroku-connect AND tag IS present
jobs:
  include:
  - stage: test
  - stage: deploy
    install: skip
    before_script: skip
    script: skip
    python: '3.6'
    env: skip
    deploy:
      provider: pypi
      user: codingjoe
      distributions: sdist bdist_wheel
      password:
        secure: jJSnEnmQgSJasFJkzvdf4SEC8l2FDHQGFp71lGdcbwx0jUEHQm2G13LDVrK31J8iQyk3jlnVJz9EA3MD3P2L06aOcj+71iG6/jtSLfECwRbc1FqltGy7Q746Wcgq+AaBpJq7qCzY/RK2WO1VDXgiyy1xr/2NpldlrGN43Ba9rs8E/ej6WpBeyBC+yCilRGQallLqHXYGHVD3Udsd+QAj0UsenXOtpw0Rz4UZHcphDLKmUIWiAqR+ibbcdyCbm8iLdXMNneDbGHdEWFiiO6hOLEuiG0FY06CTOH/DCqOV2spZTbG5TPk+iURjiI/x+K0AKFKe0Re9889lydQbe9mXjhQ9foU9dI9PS99MM4aTe7LPYWN9fCZV6CeSSlvV7ogwFuPIT51xU2VP9IA5Io103UmDbJcG/HxGwdL7/hEKJgdjxcwG8CpZrWwZl/Xsu6NoBE7CE8mbnwLkcjRs20oWapXUbwml4+5dA3XM41opzt3CXIDT2lo/kVZ/z+VlSpxqu3O3MOGgT6ywN+l+PXOjSTSbPaTmp6xjVBc8BMGRWabxpafXjBNoQfpN99TuX1iLKQXb1XNKxCCpKdUXt76RVdCpkgDMga/2rauxvfIU3URdH16uCxsMFXx+CsGums5esChZRaOFq1z80DrYyX/91wB5bxYRKyM34XplmvQ2JQo=
      on:
        tags: true
        repo: Thermondo/django-heroku-connect
