# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/entity/model_build.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from layer_client.api import ids_pb2 as api_dot_ids__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/entity/model_build.proto',
  package='api',
  syntax='proto3',
  serialized_options=b'\n\rcom.layer.apiP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x61pi/entity/model_build.proto\x12\x03\x61pi\x1a\rapi/ids.proto\"\xcd\x04\n\nModelBuild\x12\x1d\n\x02id\x18\x01 \x01(\x0b\x32\x11.api.ModelBuildId\x12-\n\x10model_version_id\x18\x02 \x01(\x0b\x32\x13.api.ModelVersionId\x12\r\n\x05index\x18\x03 \x01(\x03\x12\x0b\n\x03uri\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x1f\n\ncreated_by\x18\x06 \x01(\x0b\x32\x0b.api.UserId\x12\x17\n\x0fstart_timestamp\x18\x07 \x01(\x03\x12\x15\n\rend_timestamp\x18\x08 \x01(\x03\x12\x34\n\ndeployment\x18\t \x01(\x0e\x32 .api.ModelBuild.DeploymentStatus\x12\x1c\n\x14\x64\x65ployment_timestamp\x18\n \x01(\x03\x12-\n\nbuild_type\x18\x0b \x01(\x0e\x32\x19.api.ModelBuild.BuildType\"T\n\tBuildType\x12\x16\n\x12\x42UILD_TYPE_INVALID\x10\x00\x12\x15\n\x11\x42UILD_TYPE_AD_HOC\x10\x01\x12\x18\n\x14\x42UILD_TYPE_SCHEDULED\x10\x02\"\x95\x01\n\x10\x44\x65ploymentStatus\x12\x1d\n\x19\x44\x45PLOYMENT_STATUS_INVALID\x10\x00\x12\x1e\n\x1a\x44\x45PLOYMENT_STATUS_DEPLOYED\x10\x01\x12!\n\x1d\x44\x45PLOYMENT_STATUS_NONDEPLOYED\x10\x02\x12\x1f\n\x1b\x44\x45PLOYMENT_STATUS_DEPLOYING\x10\x03\x42\x11\n\rcom.layer.apiP\x01\x62\x06proto3'
  ,
  dependencies=[api_dot_ids__pb2.DESCRIPTOR,])



_MODELBUILD_BUILDTYPE = _descriptor.EnumDescriptor(
  name='BuildType',
  full_name='api.ModelBuild.BuildType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUILD_TYPE_INVALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BUILD_TYPE_AD_HOC', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BUILD_TYPE_SCHEDULED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=406,
  serialized_end=490,
)
_sym_db.RegisterEnumDescriptor(_MODELBUILD_BUILDTYPE)

_MODELBUILD_DEPLOYMENTSTATUS = _descriptor.EnumDescriptor(
  name='DeploymentStatus',
  full_name='api.ModelBuild.DeploymentStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEPLOYMENT_STATUS_INVALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEPLOYMENT_STATUS_DEPLOYED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEPLOYMENT_STATUS_NONDEPLOYED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEPLOYMENT_STATUS_DEPLOYING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=493,
  serialized_end=642,
)
_sym_db.RegisterEnumDescriptor(_MODELBUILD_DEPLOYMENTSTATUS)


_MODELBUILD = _descriptor.Descriptor(
  name='ModelBuild',
  full_name='api.ModelBuild',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='api.ModelBuild.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_version_id', full_name='api.ModelBuild.model_version_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='api.ModelBuild.index', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uri', full_name='api.ModelBuild.uri', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='api.ModelBuild.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created_by', full_name='api.ModelBuild.created_by', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_timestamp', full_name='api.ModelBuild.start_timestamp', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_timestamp', full_name='api.ModelBuild.end_timestamp', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deployment', full_name='api.ModelBuild.deployment', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deployment_timestamp', full_name='api.ModelBuild.deployment_timestamp', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='build_type', full_name='api.ModelBuild.build_type', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MODELBUILD_BUILDTYPE,
    _MODELBUILD_DEPLOYMENTSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=642,
)

_MODELBUILD.fields_by_name['id'].message_type = api_dot_ids__pb2._MODELBUILDID
_MODELBUILD.fields_by_name['model_version_id'].message_type = api_dot_ids__pb2._MODELVERSIONID
_MODELBUILD.fields_by_name['created_by'].message_type = api_dot_ids__pb2._USERID
_MODELBUILD.fields_by_name['deployment'].enum_type = _MODELBUILD_DEPLOYMENTSTATUS
_MODELBUILD.fields_by_name['build_type'].enum_type = _MODELBUILD_BUILDTYPE
_MODELBUILD_BUILDTYPE.containing_type = _MODELBUILD
_MODELBUILD_DEPLOYMENTSTATUS.containing_type = _MODELBUILD
DESCRIPTOR.message_types_by_name['ModelBuild'] = _MODELBUILD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelBuild = _reflection.GeneratedProtocolMessageType('ModelBuild', (_message.Message,), {
  'DESCRIPTOR' : _MODELBUILD,
  '__module__' : 'api.entity.model_build_pb2'
  # @@protoc_insertion_point(class_scope:api.ModelBuild)
  })
_sym_db.RegisterMessage(ModelBuild)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
