[tool.poetry]
name = "fastapi-pagination"
version = "0.3.0"
description = "FastAPI pagination"
authors = [
    "Yurii Karabas <1998uriyyo@gmail.com>",
]

license = "MIT"
readme = "README.md"
repository = "https://github.com/uriyyo/fastapi-pagination"

classifiers = [
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3 :: Only',
]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.7.2"
fastapi = "^0.61.2"
gino = { version = "^1.0.1", optional = true }
SQLAlchemy = { version = "^1.3.20", optional = true }
sqlalchemy-stubs = { version = "^0.3", optional = true }
databases = { version = "^0.4.0", optional = true }
orm = { version = "^0.1.5", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"
pre-commit = "^2.8.2"

[tool.poetry.extras]
gino = ["gino", "SQLAlchemy", "sqlalchemy-stubs"]
sqlalchemy = ["SQLAlchemy", "sqlalchemy-stubs"]
databases = ["databases"]
orm = ["orm"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''