language: python
dist: xenial
python: 3.6
compiler: gcc
matrix:
  include:
    - python: 3.7
      env:
      - TOX_ENV=py37
    - python: 3.8
      env:
      - TOX_ENV=py38
    - python: 3.9-dev
      env:
      - TOX_ENV=py39
addons:
  apt:
    packages:
        - pypy-dev
        - liblapack-dev
env:
 - TOX_ENV=py36
 - TOX_ENV=docs
 - TOX_ENV=flake8
 - TOX_ENV=pypy3
install:
 - |
        if [[ "${TOX_ENV}" = pypy3 ]]; then
            rm -rf ~/.pyenv
            git clone https://github.com/yyuu/pyenv.git ~/.pyenv
            PYENV_ROOT="$HOME/.pyenv"
            PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init -)"
            pyenv install pypy3.6-7.1.1
            pyenv global pypy3.6-7.1.1
        fi
 - pip install tox
script:
 - tox -e $TOX_ENV
