name: Test

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install this Package
        run: pip3 install .

      - name: Install mypy & pytest
        run: pip3 install mypy pytest

      - name: Run type check
        continue-on-error: true
        run: mypy .

      - name: Run tests
        run: pytest
