[tool.poetry]
name = "filecheck"
version = "0.0.17"
description = "Python port of LLVM's FileCheck, flexible pattern matching file verifier"
authors = ["Stanislav Pankevich <s.pankevich@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
lit = "^0.9"
bump2version = "0.5.11"
invoke = "1.3.0"

[tool.poetry.scripts]
filecheck = "filecheck.FileCheck:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

