general:
    parallel_search: True
    parallel_fully_train: True

pipeline: [nas, fully_train]

nas:
    pipe_step:
        type: NasPipeStep

    search_algorithm:
        type: AutoLaneNas
        codec: AutoLaneNasCodec
        random_ratio: 0.5
        num_mutate: 20
        max_sample: 5000
        min_sample: 50
        flops_ceiling_set_by_GFlops: 1
    search_space:
        hyperparameters:
            -   key: network.backbone.base_depth
                type: CATEGORY
                range: [18, ]
            -   key: network.backbone.type
                type: CATEGORY
                range: [ResNetVariantDet, ResNeXtVariantDet]
            -   key: network.backbone.base_channel
                type: CATEGORY
                range:  [32, ]
            -   key: network.neck.arch_code
                type: CATEGORY
                range: ['012-022', '012-122', '122-022','-']
            -   key: network.neck.type
                type: CATEGORY
                range: [FeatureFusionModule]

    model:
        model_desc:
            modules: ['backbone','neck']
            backbone:
                type: [ResNetVariantDet, ResNeXtVariantDet]
            neck:
                type: FeatureFusionModule

    trainer:
        type: Trainer
        save_model_desc: True
        with_valid: True
        is_detection_trainer: True
        callbacks: ['AutoLaneTrainerCallback','DetectionMetricsEvaluator','DetectionProgressLogger']
        lr_adjustment_position: 'after_train_step'
        report_freq: 50
        valid_interval: 10
        epochs: 20  # truth is 40
        optimizer:
            type: SGD
            params:
                lr: 0.02
                momentum: 0.9
                weight_decay: 0.0001
        lr_scheduler:
            type: WarmupScheduler
            params:
                by_epoch: False
                warmup_type: linear
                warmup_iters: 5000
                warmup_ratio: 0.1
                after_scheduler_by_epoch: False
                after_scheduler_config:
                    type: CosineAnnealingLR
                    T_max: 120000 # int(10_0000/batch_size)*epoch-warmup_iters
        metric:
            type: LaneMetric
            params:
                method: f1_measure
                eval_width: 1640
                eval_height: 590
                iou_thresh: 0.5
                lane_width: 30
                thresh_list:  [0.56, 0.60, 0.63, 0.66, 0.70, 0.73, 0.76, 0.80, 0.83, 0.86, 0.90, 0.93]

    dataset:
        type: AutoLaneDataset
        common:
            network_input_width: 512
            network_input_height: 288
            gt_len: 145
            gt_num: 576
            batch_size: 32
            num_workers: 12
            data_path: /cache/datasets/CULane/
            dataset_format: CULane
        train:
            with_aug: False
            shuffle: True
            random_sample: True
        valid:
            shuffle: False
        test:
            shuffle: False

fully_train:
    pipe_step:
        type: FullyTrainPipeStep
        models_folder: "{local_base_path}/output/nas/"
    trainer:
        type: Trainer
        is_detection_trainer: True
        valid_interval: 100
        callbacks: ['AutoLaneTrainerCallback','DetectionMetricsEvaluator','DetectionProgressLogger']
        report_freq: 50
        epochs: 3  # truth is 40
        lr_adjustment_position: 'after_train_step'
        optimizer:
            type: SGD
            params:
                lr: 0.02
                momentum: 0.9
                weight_decay: 0.0001
        lr_scheduler:
            type: WarmupScheduler
            params:
                by_epoch: False
                warmup_type: linear
                warmup_iters: 5000
                warmup_ratio: 0.1
                after_scheduler_by_epoch: False
                after_scheduler_config:
                    type: CosineAnnealingLR
                    T_max: 120000 # int(10_0000/batch_size)*epoch-warmup_iters
        metric:
            type: LaneMetric
            params:
                method: f1_measure
                eval_width: 1640
                eval_height: 590
                iou_thresh: 0.5
                lane_width: 30
                thresh_list:  [0.56, 0.60, 0.63, 0.66, 0.70, 0.73, 0.76, 0.80, 0.83, 0.86, 0.90, 0.93]

    dataset:
        type: AutoLaneDataset
        common:
            network_input_width: 512
            network_input_height: 288
            gt_len: 145
            gt_num: 576
            batch_size: 32
            num_workers: 12
            dataset_format: CULane
            data_path: /cache/datasets/CULane/
        train:
            with_aug: True
            shuffle: True
            random_sample: True
        valid:
            shuffle: False
        test:
            shuffle: False

benchmark:
    nas:
        search_space:
            hyperparameters:
                -   key: network.backbone.base_depth
                    type: CATEGORY
                    range: [18, 34, 50, 101]
                -   key: network.backbone.type
                    type: CATEGORY
                    range: [ResNetVariantDet, ResNeXtVariantDet]
                -   key: network.backbone.base_channel
                    type: CATEGORY
                    range:  [32, 48, 56, 64]
                -   key: network.neck.arch_code
                    type: CATEGORY
                    range: ['012-022', '012-122', '122-022','-']
                -   key: network.neck.type
                    type: CATEGORY
                    range: [FeatureFusionModule]

        model:
            model_desc:
                modules: ['backbone','neck']
                backbone:
                    type: [ResNetVariantDet, ResNeXtVariantDet]
                neck:
                    type: FeatureFusionModule
        trainer:
            epoch: 40
            metric:
                thresh_list:  [0.50, 0.60, 0.70, 0.80, 0.90]
    fully_train:
        trainer:
            epochs: 40
            metric:
                thresh_list:  [0.50, 0.60, 0.70, 0.80, 0.90]
