
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-12T20:03:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "dbd5bd921adeb6ae45705bece9a96de8691fc387",
 "version": "0.3.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
