[tool.poetry]
name = "mentaws"
version = "0.5.0"
description = "moMENTary AWS credentials"
authors = ["keithrozario <keith@keithrozario.com>"]

[tool.poetry.dependencies]
python = "^3.6"
boto3 = "^1.14.20"
cryptography = "^2.9.2"
PyYAML = "^5.3.1"
keyring = "^21.4.0"
pytest-cov = "^2.10.1"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
black = "^20.8b1"

[tool.poetry.scripts]
mentaws = "mentaws.main:main"
mts = "mentaws.main:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
