
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-18T17:17:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "372edd10ecf23a24da47bb23bdfb575bcfa62242",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
