- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python36-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-tox-unit-with-driver-libs
        - ironic-tox-unit-with-driver-libs-python3
        - ironic-standalone
        - ironic-tempest-functional-python2
        - ironic-tempest-functional-python3
        - ironic-grenade-dsvm
        # Disable to get the fix for other jobs
        - ironic-grenade-dsvm-multinode-multitenant:
            voting: false
        - ironic-tempest-ipa-partition-pxe_ipmitool-tinyipa-python3
        - ironic-tempest-ipa-partition-redfish-tinyipa
        - ironic-tempest-ipa-partition-uefi-pxe_ipmitool-tinyipa
        - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode:
            voting: false
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-tinyipa-indirect
        - ironic-tempest-ipa-partition-bios-agent_ipmitool-tinyipa-indirect
        - ironic-tempest-bfv
        # Non-voting jobs
        - ironic-tempest-ipa-wholedisk-bios-pxe_snmp-tinyipa:
            voting: false
        - ironic-inspector-tempest:
            voting: false
        - bifrost-integration-tinyipa-ubuntu-xenial:
            voting: false
        - metalsmith-integration-glance-localboot-centos7:
            voting: false
        - ironic-tempest-pxe_ipmitool-postgres:
            voting: false
    gate:
      queue: ironic
      jobs:
        - ironic-tox-unit-with-driver-libs
        - ironic-tox-unit-with-driver-libs-python3
        - ironic-standalone
        - ironic-tempest-functional-python2
        - ironic-tempest-functional-python3
        - ironic-grenade-dsvm
        # - ironic-grenade-dsvm-multinode-multitenant
        - ironic-tempest-ipa-partition-pxe_ipmitool-tinyipa-python3
        - ironic-tempest-ipa-partition-redfish-tinyipa
        - ironic-tempest-ipa-partition-uefi-pxe_ipmitool-tinyipa
        # - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-tinyipa-indirect
        - ironic-tempest-ipa-partition-bios-agent_ipmitool-tinyipa-indirect
        - ironic-tempest-bfv
