[tool.poetry]
name = "har2tree"
version = "1.2.10"
description = "HTTP Archive (HAR) to ETE Toolkit generator"
authors = ["Raphaël Vinot <raphael.vinot@circl.lu>"]
license = "BSD-3-Clause"
repository = "https://github.com/Lookyloo/har2tree"

readme = "README.md"

classifiers = [
    'License :: OSI Approved :: BSD License',
	'Operating System :: POSIX :: Linux',
	'Intended Audience :: Science/Research',
	'Intended Audience :: Telecommunications Industry',
	'Intended Audience :: Information Technology',
	'Programming Language :: Python :: 3',
	'Topic :: Security',
	'Topic :: Internet'
]

[tool.poetry.dependencies]
python = "^3.7"
ete3 = "^3.1.1"
beautifulsoup4 = "^4.8.2"
lxml = "^4.4.2"
six = "^1.14.0"
publicsuffix2 = "^2.20191221"
filetype = "^1.0.7"
numpy = "^1.19.1"

[tool.poetry.dev-dependencies]
coverage = "^5.3"
coveralls = "^2.1.2"
codecov = "^2.1.10"
mypy = "^0.790"
nose = "^1.3.7"
ipython = "^7.19.0"

[build-system]
requires = ["poetry_core>=1.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
