# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csnews_multilingual', '0006_tagtranslation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletranslation',
            name='master',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='csnews_multilingual.Article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photoextendedtranslation',
            name='master',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='csnews_multilingual.PhotoExtended'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='master',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='csnews_multilingual.Tag'),
            preserve_default=False,
        ),
    ]
