[tool.poetry]
name = "arcane-googleads"
version = "1.0.2"
description = "Package description"
readme = "README.md"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.7"
arcane-core = "^1.0.8"
backoff = "1.10.0"
google-ads = "^7.0.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
