jobs:
  include:
  - os: linux
    language: python
    python: 3.8
    dist: xenial
    sudo: true
    env:
    - BUILD=PYPI
    - DIST=linux
  - os: osx
    osx_image: xcode12
    env:
    - DIST=osx
  - os: windows
    language: shell
    before_install:
      - choco install python --version 3.8.0
      - python -m pip install --upgrade pip
    env:
      - PATH=/c/Python38:/c/Python38/Scripts:$PATH
      - DIST=windows
install:
- pip3 install -r requirements/dev.txt
- pip3 install -r requirements/test.txt
- pip3 install flake8 pyinstaller
script:
- flake8
- pytest
- ./package.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: pypi
    skip_cleanup: true
    skip_existing: true
    user: __token__
    password:
      secure: N01wX+AKR6A5LZbpcGK+QRIunHurSq8kn/YC0+c8h31hS+LaliZXvGvBVAhAig0v6yRSTXz0j0cf3rcR+xCQozCI56diPpcmd0nLXd0L6XYifN5KbmkKW1x/CDnaIhWzLU6KTHR2KdZYPnLJMPwtH8NMWIF5ExFCyaZVsUeFfXYicV2gPAQW8J2R4uUvjGTJLreeO4f1IWKp0iN0euiQmA5BknOkXIuqjrojxIB/Vp6xZtA40xK8m2/+aaxewLHi7YbdMJ1/gkHMk47E4Lxqfc6AEXpQRWe2VguCxRGQEnQoc5QyijYZGZ52/mhosGGDFt+CrKzmmgMdGZCzVR71R1OV5WBQOX55juesm1MecinJJAyVUvP5fqt9MXXs0uSP18XKXqrlh99/z/GnZtPxalsHqSXyrBdd7/9EiaGcegbpRahhb0G5Jo1NdjKDqp+L2lHQLKMN8DhfatdL70VOJSOynwJPTq8/E0Qc247sEpB248Bz9MzU3f40RV4S925aOelo1cdRIDE6B2+ujdP7ttIsiQhc5zEL89N5N0nRGdd1yFjS2itw51FRQNXEn8Rno066RgLRX9P5H/9ximVZokA+h+kiJ+XtFlwrdk3xcnPFb7uavCF338aXMWeE6OzN7wBSbqXzFPTEJjo90VWE/x2x9LeBUdWlXTcgBhx31no=
    on:
      tags: true
      all_branches: true
      distributions: sdist
      condition: "$BUILD = PYPI"
      repo: cloudblue/connect-cli
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: LYs1vRe6aIL1GQ9HY3HGYxkeSdsmk9Lncfli2LOu7tjr27w28WAlmRtmFouJJe/L4922v+DAuYD3hZReZ7sfLZQrhfUnm8C4EaEo9sHncYXq6DSdiT+R+fRbieIWObch5p2rhQUPL9t7nqxS9ZKvB1FXeNGyctNiL4Uo+MJSaK369/vBr0zymlD/sXJeN+1Ssfm1s0wuqryG0ttZxnIF/A4Me6U8WA2nWKvzchEo8vgM7k9W7PR+BinOS85nxc65mMe5THuXq2rbiB+DUs4d9Qg41SdgiR6oPDaQk69ZRyQMolGp/H6IgpQbErkBLf6VnpoydEEkKgRo0PThJ6qZCwBO71jR+DCgIsqf/iM4rvAuJ2DnuVgkKjdRiwOwBJqZIBxSqyq6J5JBixHAlFHM2rux0UjLXVbt404UzIbmXLYndhsak/WjGWhDOYeOhSqKIreF+3Gpd5Drg1JhApOshNNG1p7PfH4e1OeujLeF+9xoBKwJvE6ljkZaYQkDUhw0NK51sxHyB0bUQzHD+gSvkA1mAv68Ko/bKGbqqJ7soBxYeNNKrYEZvgYA3OALgfEEBo9R7Zk0Iw7IesiyT9Bz6wLp1AU62IDoaqqgeVWYEPSrqUjqMEgsClUFu/S7JEpRfJGZi8N/zkjApA7MF4GDkVA/BSiYl4wBFfR9xXr9hG8=
    file: "connect-cli_${TRAVIS_TAG}_${TRAVIS_OS_NAME}_${TRAVIS_CPU_ARCH}.tar.gz"
    on:
      tags: true
      condition: "$DIST = linux"
      repo: cloudblue/connect-cli
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: LYs1vRe6aIL1GQ9HY3HGYxkeSdsmk9Lncfli2LOu7tjr27w28WAlmRtmFouJJe/L4922v+DAuYD3hZReZ7sfLZQrhfUnm8C4EaEo9sHncYXq6DSdiT+R+fRbieIWObch5p2rhQUPL9t7nqxS9ZKvB1FXeNGyctNiL4Uo+MJSaK369/vBr0zymlD/sXJeN+1Ssfm1s0wuqryG0ttZxnIF/A4Me6U8WA2nWKvzchEo8vgM7k9W7PR+BinOS85nxc65mMe5THuXq2rbiB+DUs4d9Qg41SdgiR6oPDaQk69ZRyQMolGp/H6IgpQbErkBLf6VnpoydEEkKgRo0PThJ6qZCwBO71jR+DCgIsqf/iM4rvAuJ2DnuVgkKjdRiwOwBJqZIBxSqyq6J5JBixHAlFHM2rux0UjLXVbt404UzIbmXLYndhsak/WjGWhDOYeOhSqKIreF+3Gpd5Drg1JhApOshNNG1p7PfH4e1OeujLeF+9xoBKwJvE6ljkZaYQkDUhw0NK51sxHyB0bUQzHD+gSvkA1mAv68Ko/bKGbqqJ7soBxYeNNKrYEZvgYA3OALgfEEBo9R7Zk0Iw7IesiyT9Bz6wLp1AU62IDoaqqgeVWYEPSrqUjqMEgsClUFu/S7JEpRfJGZi8N/zkjApA7MF4GDkVA/BSiYl4wBFfR9xXr9hG8=
    file: "connect-cli_${TRAVIS_TAG}_${TRAVIS_OS_NAME}_${TRAVIS_CPU_ARCH}.tar.gz"    
    on:
      tags: true
      condition: "$DIST = osx"
      repo: cloudblue/connect-cli
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: LYs1vRe6aIL1GQ9HY3HGYxkeSdsmk9Lncfli2LOu7tjr27w28WAlmRtmFouJJe/L4922v+DAuYD3hZReZ7sfLZQrhfUnm8C4EaEo9sHncYXq6DSdiT+R+fRbieIWObch5p2rhQUPL9t7nqxS9ZKvB1FXeNGyctNiL4Uo+MJSaK369/vBr0zymlD/sXJeN+1Ssfm1s0wuqryG0ttZxnIF/A4Me6U8WA2nWKvzchEo8vgM7k9W7PR+BinOS85nxc65mMe5THuXq2rbiB+DUs4d9Qg41SdgiR6oPDaQk69ZRyQMolGp/H6IgpQbErkBLf6VnpoydEEkKgRo0PThJ6qZCwBO71jR+DCgIsqf/iM4rvAuJ2DnuVgkKjdRiwOwBJqZIBxSqyq6J5JBixHAlFHM2rux0UjLXVbt404UzIbmXLYndhsak/WjGWhDOYeOhSqKIreF+3Gpd5Drg1JhApOshNNG1p7PfH4e1OeujLeF+9xoBKwJvE6ljkZaYQkDUhw0NK51sxHyB0bUQzHD+gSvkA1mAv68Ko/bKGbqqJ7soBxYeNNKrYEZvgYA3OALgfEEBo9R7Zk0Iw7IesiyT9Bz6wLp1AU62IDoaqqgeVWYEPSrqUjqMEgsClUFu/S7JEpRfJGZi8N/zkjApA7MF4GDkVA/BSiYl4wBFfR9xXr9hG8=
    file: "connect-cli_${TRAVIS_TAG}_${TRAVIS_OS_NAME}_${TRAVIS_CPU_ARCH}.zip"    
    on:
      tags: true
      condition: "$DIST = windows"
      repo: cloudblue/connect-cli
