- hosts: all
  tasks:

    - name: Ensure artifacts directory exists
      file:
        path: '{{ zuul.executor.work_root }}/artifacts/{{ image_name }}/files'
        state: directory
      delegate_to: localhost

    - name: Copy files from {{ ansible_user_dir }}/src/opendev.org/openstack/ironic-python-agent on node
      synchronize:
        src: '{{ ansible_user_dir }}/src/opendev.org/openstack/ironic-python-agent/UPLOAD_RAW/'
        dest: '{{ zuul.executor.work_root }}/artifacts/{{ image_name }}/files/'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=/*
          - --prune-empty-dirs

    - name: Copy files from {{ ansible_user_dir }}/src/opendev.org/openstack/ironic-python-agent on node
      synchronize:
        src: '{{ ansible_user_dir }}/src/opendev.org/openstack/ironic-python-agent/UPLOAD_TAR/'
        dest: '{{ zuul.executor.work_root }}/artifacts/{{ image_name }}/'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=/*
          - --prune-empty-dirs

    - name: Copy files from {{ ansible_user_dir }}/src/opendev.org/openstack/ironic-python-agent on node
      synchronize:
        src: '{{ ansible_user_dir }}/src/opendev.org/openstack/ironic-python-agent/'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=/testrepository.subunit.gz
          - --include=*/
          - --exclude=*
          - --prune-empty-dirs
