- hosts: all
  tasks:
    - shell:
        cmd: |
          set -e
          set -x
          BRANCH={{ zuul.branch }}
          export BRANCH_PATH=`echo $BRANCH | tr / -`

          mkdir UPLOAD_RAW
          mkdir UPLOAD_TAR

          JOBNAME='ironic-python-agent-buildimage-{{ image_name }}'
          TRANS_START_TIME=$(date +%s)
          SUBUNIT_OUTPUT=testrepository.subunit
          ERRORS=1
          VENV=$(mktemp -d)
          virtualenv $VENV
          $VENV/bin/pip install -U os-testr

          trap "finish" EXIT

          function finish {
              if [[ "$ERRORS" -eq 1 ]]; then
                  $VENV/bin/generate-subunit $TRANS_START_TIME $SECONDS 'fail' $JOBNAME >> $SUBUNIT_OUTPUT
              else
                  $VENV/bin/generate-subunit $TRANS_START_TIME $SECONDS 'success' $JOBNAME >> $SUBUNIT_OUTPUT
              fi
              gzip -9 $SUBUNIT_OUTPUT
              if [ "$VENV" != "" ] ; then
                  rm -rf $VENV
                  VENV=""
              fi
          }

          type='{{ image_name }}'
          case $type in
              tinyipa)
                  export BUILD_AND_INSTALL_TINYIPA=true
                  (cd imagebuild/tinyipa && make)
                  mv imagebuild/tinyipa/tinyipa*.tar.gz* UPLOAD_TAR
                  mv imagebuild/tinyipa/tinyipa*.* UPLOAD_RAW
                  mv imagebuild/tinyipa/tiny-instance-uec*.tar.gz UPLOAD_TAR
                  # NOTE(sambetts) Must clean up chroot directories before
                  # publisher rsync command tries and fails to read them
                  (cd imagebuild/tinyipa && make clean)
              ;;
              coreos)
                  imagebuild/coreos/full_trusty_build.sh
                  mv imagebuild/coreos/UPLOAD/coreos_production_pxe* UPLOAD_RAW
                  mv ipa-coreos*.tar.gz* UPLOAD_TAR
              ;;
          esac
          ERRORS=0
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/src/opendev.org/openstack/ironic-python-agent'
