repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: check-docstring-first
        -   id: check-merge-conflict
        -   id: debug-statements
    -   repo: https://github.com/psf/black
        rev: 19.3b0
        hooks:
        -   id: black
    -   repo: https://github.com/pycqa/isort
        rev: 5.5.2
        hooks:
        -   id: isort
            args: ["-m3", "--trailing-comma"]
