[tool.poetry]
name = "ream"
version = "0.1.3.3"
description = "parser/dumper for REAM files"
authors = ["Chih-Ming Louis Lee <louis@chihminglee.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/chmlee/ream-python"
classifiers = [
    "Topic :: Scientific/Engineering",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 3 - Alpha"
]

packages = [
  {include = "ream"}
]

[tool.poetry.dependencies]
python = "^3.6.1"
pandas = "^1.0.4"
lark = "^0.0.4"

[tool.poetry.dev-dependencies]
pytest = "^3.4"

[tool.poetry.scripts]
ream = "ream.commandline:main"
