# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import score_pb2 as score__pb2


class ScoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AppScore = channel.unary_unary(
                '/score.ScoreService/AppScore',
                request_serializer=score__pb2.ScoreRequest.SerializeToString,
                response_deserializer=score__pb2.QueryResponse.FromString,
                )
        self.GetPreAppScore = channel.unary_unary(
                '/score.ScoreService/GetPreAppScore',
                request_serializer=score__pb2.PreLoanRequest.SerializeToString,
                response_deserializer=score__pb2.PreLoanResponse.FromString,
                )
        self.GetOrderPreAppScore = channel.unary_unary(
                '/score.ScoreService/GetOrderPreAppScore',
                request_serializer=score__pb2.OrderPreLoanRequest.SerializeToString,
                response_deserializer=score__pb2.OrderPreLoanResponse.FromString,
                )


class ScoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AppScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPreAppScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderPreAppScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AppScore': grpc.unary_unary_rpc_method_handler(
                    servicer.AppScore,
                    request_deserializer=score__pb2.ScoreRequest.FromString,
                    response_serializer=score__pb2.QueryResponse.SerializeToString,
            ),
            'GetPreAppScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPreAppScore,
                    request_deserializer=score__pb2.PreLoanRequest.FromString,
                    response_serializer=score__pb2.PreLoanResponse.SerializeToString,
            ),
            'GetOrderPreAppScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderPreAppScore,
                    request_deserializer=score__pb2.OrderPreLoanRequest.FromString,
                    response_serializer=score__pb2.OrderPreLoanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'score.ScoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ScoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AppScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/score.ScoreService/AppScore',
            score__pb2.ScoreRequest.SerializeToString,
            score__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPreAppScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/score.ScoreService/GetPreAppScore',
            score__pb2.PreLoanRequest.SerializeToString,
            score__pb2.PreLoanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderPreAppScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/score.ScoreService/GetOrderPreAppScore',
            score__pb2.OrderPreLoanRequest.SerializeToString,
            score__pb2.OrderPreLoanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
