general:
    parallel_search: True
    parallel_fully_train: True
    backend: pytorch

pipeline: [random, mutate]
# pipeline: [random, mutate, fully_train]

random:
    pipe_step:
        type: NasPipeStep

    dataset:
        type: DIV2K
        common:
            value_div: 255.0
        train:
            root_HR: /cache/datasets/DIV2K/div2k_train/hr
            root_LR: /cache/datasets/DIV2K/div2k_train/lr
            upscale: 2
            crop: 64    # crop size of lr image
            hflip: true    # flip image horizontally
            vflip: true    # flip image vertically
            rot90: true    # flip image diagonally
            shuffle: true
            num_workers: 2
            batch_size: 16
            pin_memory: false
        test:
            root_HR: /cache/datasets/DIV2K/div2k_valid/hr
            root_LR: /cache/datasets/DIV2K/div2k_valid/lr
            upscale: 2
            crop: 64
            pin_memory: false
    search_space:
        type: SearchSpace
        modules: ['custom']
        custom:
            type: MtMSR
            in_channel: 3
            out_channel: 3
            upscale: 2
            rgb_mean: [0.4040, 0.4371, 0.4488]
            candidates: [res2, res3]
            block_range: [10, 80]
            cib_range: [3, 4]

    search_algorithm:
        type: SRRandom
        codec: SRCodec
        policy:
            num_sample: 3 #10

    trainer:
        type: Trainer
        epochs: 2 #50
        optimizer:
            type: Adam
            params:
                lr: 0.0004
        lr_scheduler:
            type: StepLR
            params:
                step_size: 100
                gamma: 0.5
        loss:
            type: L1Loss
        metric:
            type: SRMetric
            params:
                method: psnr
                scale: 2
        calc_params_each_epoch: True

    evaluator:
        type: Evaluator
        gpu_evaluator:
            type: GpuEvaluator
            metric:
                type: SRMetric
            load_pkl: False
    #    davinci_mobile_evaluator:
    #        type: DavinciMobileEvaluator
    #        hardware: "Bolt"
    #        remote_host: "http://192.168.0.2:8888"
    #         metric:
    #             type: SRMetric

mutate:
    pipe_step:
        type: NasPipeStep

    dataset:
        ref: random.dataset

    search_space:
        type: SearchSpace
        ref: random.search_space

    search_algorithm:
        type: SRMutate
        codec: SRCodec
        policy:
            num_mutate: 3
            num_sample: 10

    trainer:
        ref: random.trainer
        epochs: 2 #50
        save_model_desc: True

fully_train:
    pipe_step:
        type: FullyTrainPipeStep
        models_folder: "{local_base_path}/output/mutate/"
    dataset:
        ref: random.dataset
        train:
            batch_size: 50

    search_space:
        ref: random.search_space

    trainer:
        type: Trainer
        seed: 0
        epochs: 2 #10000
        optimizer:
            type: Adam
            params:
                lr: 0.0002
        lr_scheduler:
            type: StepLR
            params:
                step_size: 4000
                gamma: 0.5
        loss:
            type: L1Loss
        metric:
            type: SRMetric
            params:
                method: psnr
                scale: 2

benchmark:
    pipeline: [random, mutate, fully_train, benchmark_DIV2K, benchmark_Set5, benchmark_Set14, benchmark_BSDS100]
    random:
        search_algorithm:
            policy:
                num_sample: 1000
        trainer:
            epochs: 400
    mutate:
        search_algorithm:
            policy:
                num_sample: 1000
        trainer:
            epochs: 100
    fully_train:
        trainer:
            epochs: 20000
    benchmark_DIV2K:
        pipe_step:
            type: BenchmarkPipeStep
            models_folder: "{local_base_path}/output/fully_train/"
        dataset:
            type: DIV2K
            test:
                root_HR: /cache/datasets/DIV2K/div2k_valid/hr
                root_LR: /cache/datasets/DIV2K/div2k_train/lr
                upscale: 2
        evaluator:
            type: Evaluator
            gpu_evaluator:
                type: GpuEvaluator
                metric:
                    type: SRMetric
                    params:
                        method: psnr
                        scale: 2

    benchmark_Set5:
        pipe_step:
            type: BenchmarkPipeStep
            models_folder: "{local_base_path}/output/fully_train/"
        dataset:
            ref: benchmark_DIV2K.dataset
            type: Set5
            test:
                root_HR: /cache/datasets/DIV2K/Set5/hr
                root_LR: /cache/datasets/DIV2K/Set5/lr
        evaluator:
            ref: benchmark_DIV2K.evaluator

    benchmark_Set14:
        pipe_step:
            type: BenchmarkPipeStep
            models_folder: "{local_base_path}/output/fully_train/"
        dataset:
            ref: benchmark_DIV2K.dataset
            type: Set14
            test:
                root_HR: /cache/datasets/DIV2K/Set14/hr
                root_LR: /cache/datasets/DIV2K/Set14/lr
        evaluator:
            ref: benchmark_DIV2K.evaluator

    benchmark_BSDS100:
        pipe_step:
            type: BenchmarkPipeStep
            models_folder: "{local_base_path}/output/fully_train/"
        dataset:
            ref: benchmark_DIV2K.dataset
            type: BSDS100
            test:
                root_HR: /cache/datasets/DIV2K/BSDS100/hr
                root_LR: /cache/datasets/DIV2K/BSDS100/lr
        evaluator:
            ref: benchmark_DIV2K.evaluator      