site_name: Code Video Generator
docs_dir: docs/src
theme:
    name: readthedocs
    custom_dir: docs/theme/

nav:
    - Home: index.md
    - Installation: installation.md
    - GitHub: https://github.com/sleuth-io/code-video-generator
    - About: about.md
