
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-13T23:13:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "66cb545ad48a39eed57aa01830bfae470d09c97c",
 "version": "1.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
