[tool.poetry]
name = "Salient"
version = "0.1.1"
description = "Salient: A simple SqlAlchemy Linter."
authors = ["Tom Faulkner <faulkner@pm.me>"]
readme = "README.md"
homepage = "https://github.com/TomFaulkner/sa_lint"

[tool.poetry.dependencies]
python = ">=3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-asyncio = "^0.14.0"
black = "^20.8b1"

[tool.poetry.scripts]
salient = 'salient.salient:cmd'
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}