[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ubatch"
version = "0.0.2"
description = "Micro batch solution for improve throughput in SIMD processes"
authors = ["Rodolfo E. Edelmann <redelmann@mercadolibre.com>"]
maintainers = ["Leandro E. Colombo Viña <leandro.colombo@mercadolibre.com>"]
include = ["ubatch/py.typed"]
classifiers=[
  "Intended Audience :: Developers",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
]
repository = "https://github.com/mercadolibre/ubatch"
homepage = "https://github.com/mercadolibre/ubatch"

license = "Apache-2.0"
readme = "README.md"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/mercadolibre/ubatch/issues"

[tool.poetry.dependencies]
python = "^3.6"
flask-restx = { version = "^0.2", optional = true }
scikit-learn = { version = "^0.23", optional = true }
gunicorn = { version = "^20.0", optional = true }
xgboost = { version = "^1.2", optional = true }
keras = { version = "^2.4", optional = true }
tensorflow = { version = "^2.3", optional = true }

[tool.poetry.dev-dependencies]
black = "*"
flake8 = "*"
mypy = "*"
bandit = "^1.6"
pre-commit = "*"
pytest = "^6.1"
pytest-cov = "^2.10"
pytest-freezegun = "^0.4"
pytest-mock = "^3.3"
pytest-timeout = "^1.4"
pytest-reraise = "^1.0"

[tool.poetry.extras]
benchmark = ["flask-restx", "scikit-learn", "gunicorn", "xgboost", "keras", "tensorflow"]

[tool.black]
line-length = 88
