[tool.poetry]
name = "diff-1c"
version = "6.5.2"
description = "Diff utility for 1C:Enterprise"
authors = ["Cujoko <cujoko@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Cujoko/diff-1c"
keywords = ["1c", "diff", "v8reader", "v8unpack", "gcomp"]
classifiers=[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: Russian",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development",
    "Topic :: Utilities"
]

[tool.poetry.scripts]
diff1c = "diff_1c.__main__:run"

[tool.poetry.dependencies]
python = "^3.9"
cjk-commons = "^3.5"
parse-1c-build = "^5.14"
loguru = "^0.5"

[tool.poetry.dev-dependencies]
pylint = "^2.6"
pytest = "^6.1"
rope = "^0.18"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
